// eslint-disable-next-line no-unused-vars
function findHug(ran) {
	switch(ran) {
	case 1:
		return 'https://media1.tenor.com/images/aeb42019b0409b98aed663f35b613828/tenor.gif?itemid=14108949';
	case 2:
		return 'https://media1.tenor.com/images/78d3f21a608a4ff0c8a09ec12ffe763d/tenor.gif?itemid=16509980';
	case 3:
		return 'https://media1.tenor.com/images/1069921ddcf38ff722125c8f65401c28/tenor.gif?itemid=11074788';
	case 4:
		return 'https://media1.tenor.com/images/969f0f462e4b7350da543f0231ba94cb/tenor.gif?itemid=14246498';
	case 5:
		return 'https://media1.tenor.com/images/4db088cfc73a5ee19968fda53be6b446/tenor.gif?itemid=14637016';
	case 6:
		return 'https://media1.tenor.com/images/e58eb2794ff1a12315665c28d5bc3f5e/tenor.gif?itemid=10195705';
	case 7:
		return 'https://media1.tenor.com/images/6db54c4d6dad5f1f2863d878cfb2d8df/tenor.gif?itemid=7324587';
	case 8:
		return 'https://media1.tenor.com/images/506aa95bbb0a71351bcaa753eaa2a45c/tenor.gif?itemid=7552075';
	case 9:
		return 'https://media1.tenor.com/images/b77fd0cfd95f89f967be0a5ebb3b6c6a/tenor.gif?itemid=7864716';
	}
}

/* eslint-disable brace-style */
function gambleRoll(ran) {
	switch(ran) {
	// 1-5 = apple, 6-9 = cherry, 10-12 = melon, 13-14 = cheese, 15 = burger
	case 1:
		return '🍎';
	case 2:
		return '🍎';
	case 3:
		return '🍎';
	case 4:
		return '🍎';
	case 5:
		return '🍎';
	case 6:
		return '🍒';
	case 7:
		return '🍒';
	case 8:
		return '🍒';
	case 9:
		return '🍒';
	case 10:
		return '🍉';
	case 11:
		return '🍉';
	case 12:
		return '🍉';
	case 13:
		return '🧀';
	case 14:
		return '🧀';
	case 15:
		return '🍔';
	}
}

function gambleValue(ran) {
	switch(ran) {
	// 1-5 = apple, 6-9 = cherry, 10-12 = melon, 13-14 = cheese, 15 = burger
	case 1:
		return 1;
	case 2:
		return 1;
	case 3:
		return 1;
	case 4:
		return 1;
	case 5:
		return 1;
	case 6:
		return 2;
	case 7:
		return 2;
	case 8:
		return 2;
	case 9:
		return 2;
	case 10:
		return 3;
	case 11:
		return 3;
	case 12:
		return 3;
	case 13:
		return 4;
	case 14:
		return 4;
	case 15:
		return 5;
	}
}

function payout(ran1Value, ran2Value, ran3Value) {
	if(ran1Value == 1 && ran2Value == 1 && ran3Value == 1) {
		return 1.25;
	} else if(ran1Value == 2 && ran2Value == 1 && ran3Value == 1) {
		return 1;
	} else if(ran1Value == 3 && ran2Value == 1 && ran3Value == 1) {
		return 1;
	} else if(ran1Value == 4 && ran2Value == 1 && ran3Value == 1) {
		return 1;
	} else if(ran1Value == 5 && ran2Value == 1 && ran3Value == 1) {
		return 1;
	} else if(ran1Value == 1 && ran2Value == 2 && ran3Value == 1) {
		return 1;
	} else if(ran1Value == 1 && ran2Value == 3 && ran3Value == 1) {
		return 1;
	} else if(ran1Value == 1 && ran2Value == 4 && ran3Value == 1) {
		return 1;
	} else if(ran1Value == 1 && ran2Value == 5 && ran3Value == 1) {
		return 1;
	} else if(ran1Value == 1 && ran2Value == 1 && ran3Value == 2) {
		return 1;
	} else if(ran1Value == 1 && ran2Value == 1 && ran3Value == 3) {
		return 1;
	} else if(ran1Value == 1 && ran2Value == 1 && ran3Value == 4) {
		return 1;
	} else if(ran1Value == 1 && ran2Value == 1 && ran3Value == 5) {
		return 1;
	} else if(ran1Value == 2 && ran2Value == 2 && ran3Value == 2) {
		return 1.5;
	} else if(ran1Value == 3 && ran2Value == 3 && ran3Value == 3) {
		return 1.75;
	} else if(ran1Value == 4 && ran2Value == 4 && ran3Value == 4) {
		return 2;
	} else if(ran1Value == 5 && ran2Value == 5 && ran3Value == 5) {
		return 3;
	} else {
		return 0;
	}
}

function color(mult) {
	if(mult == 0) {
		return '#ff0000';
	} else {
		return '#1dde47';
	}
}

function title(titleRan) {
	switch(titleRan) {
	case 1:
		return 'I sure do love gambling';
	case 2:
		return 'I hope I didn\'t lose anything';
	case 3:
		return 'Come on jackpot';
	}
}

// eslint-disable-next-line no-unused-vars
function findGif(ran) {
	switch(ran) {
	case 1:
		return 'https://i.imgur.com/UjYq4If.gif';
	case 2:
		return 'https://i.imgur.com/6YvXWPT.gif';
	case 3:
		return 'https://i.imgur.com/ta2MK9H.gif';
	case 4:
		return 'https://i.imgur.com/G5kYj3p.gif';
	case 5:
		return 'https://i.imgur.com/tPOUxwU.gif';
	case 6:
		return 'https://i.imgur.com/zYzX0Bh.gif';
	case 7:
		return 'https://i.imgur.com/hY9rBFE.gif';
	case 8:
		return 'https://i.imgur.com/A2Lwxdu.gif';
	case 9:
		return 'https://i.imgur.com/BRojOWf.gif';
	case 10:
		return 'https://i.imgur.com/zEcL4Aw.gif';
	case 11:
		return 'https://i.imgur.com/5Y2rLP7.gif';
	case 12:
		return 'https://i.imgur.com/waiptRg.gif';
	case 13:
		return 'https://i.imgur.com/kkfFWH6.gif';
	case 14:
		return 'https://i.imgur.com/9TFyJ8k.gif';
	case 15:
		return 'https://i.imgur.com/PCpK2x8.gif';
	case 16:
		return 'https://i.imgur.com/PxerLBF.gif';
	case 17:
		return 'https://i.imgur.com/XWLfp7U.gif';
	case 18:
		return 'https://i.imgur.com/9bK4kRA.gif';
	case 19:
		return 'https://i.imgur.com/ov0C4kB.gif';
	case 20:
		return 'https://i.imgur.com/wErykSa.gif';
	case 21:
		return 'https://i.imgur.com/YV5VlW7.gif';
	case 22:
		return 'https://i.imgur.com/r0TWK8P.gif';
	case 23:
		return 'https://i.imgur.com/VSO1Tqo.gif';
	case 24:
		return 'https://i.imgur.com/134Y4Sx.gif';
	case 25:
		return 'https://i.imgur.com/ILkMhEi.gif';
	case 26:
		return 'https://i.imgur.com/JhRu30X.gif';
	case 27:
		return 'https://i.imgur.com/sN8VefM.gif';
	case 28:
		return 'https://i.imgur.com/lCHclSL.gif';
	case 29:
		return 'https://i.imgur.com/2vzflFa.gif';
	case 30:
		return 'https://i.imgur.com/Ok9sP84.gif';
	case 31:
		return 'https://i.imgur.com/5Dn8cDd.gif';
	case 32:
		return 'https://i.imgur.com/pULxg9P.gif';
	}
}

function findImage(ran) {
	switch(ran) {
	case 1:
		return 'https://i.imgur.com/yB8nFPa.png';
	case 2:
		return 'https://i.imgur.com/RQkPpNc.png';
	case 3:
		return 'https://i.imgur.com/tK3xylQ.png';
	case 4:
		return 'https://i.imgur.com/5DfUCmo.png';
	case 5:
		return 'https://i.imgur.com/w5hJwIu.png';
	case 6:
		return 'https://i.imgur.com/92B7dq9.png';
	case 7:
		return 'https://i.imgur.com/Vf6t8d2.png';
	case 8:
		return 'https://i.imgur.com/9svcmRZ.png';
	case 9:
		return 'https://i.imgur.com/ib4EscF.png';
	case 10:
		return 'https://i.imgur.com/b04curC.png';
	case 11:
		return 'https://i.imgur.com/eErEJWZ.png';
	case 12:
		return 'https://i.imgur.com/m5n68Yp.png';
	case 13:
		return 'https://i.imgur.com/h9xP7kG.png';
	case 14:
		return 'https://i.imgur.com/GwCtiuW.png';
	case 15:
		return 'https://i.imgur.com/iauofuo.png';
	case 16:
		return 'https://i.imgur.com/ETRThgb.png';
	case 17:
		return 'https://i.imgur.com/EqM3XVX.png';
	case 18:
		return 'https://i.imgur.com/dJLEyFQ.png';
	case 19:
		return 'https://i.imgur.com/fxOJmUb.png';
	case 20:
		return 'https://i.imgur.com/CLa89wI.png';
	case 21:
		return 'https://i.imgur.com/8efgXSr.png';
	case 22:
		return 'https://i.imgur.com/pF9HAxQ.png';
	case 23:
		return 'https://i.imgur.com/37r70QC.png';
	case 24:
		return 'https://i.imgur.com/UMjIdxs.png';
	case 25:
		return 'https://i.imgur.com/zgGvt5x.png';
	case 26:
		return 'https://i.imgur.com/vPP5Pet.png';
	case 27:
		return 'https://i.imgur.com/6BIEi9D.png';
	case 28:
		return 'https://i.imgur.com/Q30lZwj.png';
	case 29:
		return 'https://i.imgur.com/IeNoztA.png';
	case 30:
		return 'https://i.imgur.com/0F3Fnbk.png';
	case 31:
		return 'https://i.imgur.com/SpQpVrg.png';
	case 32:
		return 'https://i.imgur.com/1A217nh.png';
	case 33:
		return 'https://i.imgur.com/DvZxj1s.png';
	case 34:
		return 'https://i.imgur.com/tO37LHU.png';
	case 35:
		return 'https://i.imgur.com/ISr2Yak.png';
	case 36:
		return 'https://i.imgur.com/mmJuRPb.png';
	case 37:
		return 'https://i.imgur.com/SylPr89.png';
	case 38:
		return 'https://i.imgur.com/fF2XGgW.png';
	case 39:
		return 'https://i.imgur.com/lKNGQkl.png';
	case 40:
		return 'https://i.imgur.com/V1zwc1F.png';
	case 41:
		return 'https://i.imgur.com/3sa8OUL.png';
	case 42:
		return 'https://i.imgur.com/LXZkmFh.png';
	case 43:
		return 'https://i.imgur.com/eu70962.png';
	case 44:
		return 'https://i.imgur.com/zsauB8n.png';
	case 45:
		return 'https://i.imgur.com/kSxstbA.png';
	case 46:
		return 'https://i.imgur.com/joPkY3f.png';
	case 47:
		return 'https://i.imgur.com/NPQSdGR.png';
	case 48:
		return 'https://i.imgur.com/P7QSTQn.png';
	case 49:
		return 'https://i.imgur.com/7pt05jM.png';
	case 50:
		return 'https://i.imgur.com/fadipPH.png';
	case 51:
		return 'https://i.imgur.com/QEBYU6w.png';
	case 52:
		return 'https://i.imgur.com/f1EJ8Gb.png';
	case 53:
		return 'https://i.imgur.com/yHxqxUU.png';
	case 54:
		return 'https://i.imgur.com/ESW9RGd.png';
	case 55:
		return 'https://i.imgur.com/zWCaQbM.png';
	case 56:
		return 'https://i.imgur.com/pvGBY5K.png';
	case 57:
		return 'https://i.imgur.com/KW7Zwxo.png';
	case 58:
		return 'https://i.imgur.com/uPhxc6m.png';
	case 59:
		return 'https://i.imgur.com/ig6F9Zc.png';
	case 60:
		return 'https://i.imgur.com/QHpHpez.png';
	case 61:
		return 'https://i.imgur.com/2MDIRK7.png';
	case 62:
		return 'https://i.imgur.com/SyPsQUI.png';
	case 63:
		return 'https://i.imgur.com/BL1S7fj.png';
	case 64:
		return 'https://i.imgur.com/GhBmmbx.png';
	case 65:
		return 'https://i.imgur.com/sIxdRJe.png';
	case 66:
		return 'https://i.imgur.com/GkpclGW.png';
	case 67:
		return 'https://i.imgur.com/pi32vFk.png';
	case 68:
		return 'https://i.imgur.com/nkhChj9.png';
	case 69:
		return 'https://i.imgur.com/LBY0yEg.png';
	case 70:
		return 'https://i.imgur.com/4YBTh6C.png';
	case 71:
		return 'https://i.imgur.com/WTI3UUb.png';
	case 72:
		return 'https://i.imgur.com/LteyDI4.png';
	case 73:
		return 'https://i.imgur.com/z1uBTI5.png';
	case 74:
		return 'https://i.imgur.com/HhRHEFd.png';
	case 75:
		return 'https://i.imgur.com/F0lNPw1.png';
	case 76:
		return 'https://i.imgur.com/rvc0QYx.png';
	case 77:
		return 'https://i.imgur.com/KcJUE1t.png';
	case 78:
		return 'https://i.imgur.com/AMTDfea.png';
	case 79:
		return 'https://i.imgur.com/QoCHqRc.png';
	case 80:
		return 'https://i.imgur.com/NtZ0xr5.png';
	case 81:
		return 'https://i.imgur.com/SdCQXO1.png';
	case 82:
		return 'https://i.imgur.com/FmDZg19.png';
	case 83:
		return 'https://i.imgur.com/q14VfBa.png';
	case 84:
		return 'https://i.imgur.com/GYVY4CQ.png';
	case 85:
		return 'https://i.imgur.com/ObnYbWW.png';
	case 86:
		return 'https://i.imgur.com/BWslGcg.png';
	case 87:
		return 'https://i.imgur.com/4fmr6e9.png';
	case 88:
		return 'https://i.imgur.com/0CqDc7X.png';
	case 89:
		return 'https://i.imgur.com/zziffwe.png';
	case 90:
		return 'https://i.imgur.com/rJrsJ9Q.png';
	case 91:
		return 'https://i.imgur.com/ouk6zHu.png';
	case 92:
		return 'https://i.imgur.com/je11WeV.png';
	case 93:
		return 'https://i.imgur.com/IdP76qc.png';
	case 94:
		return 'https://i.imgur.com/LHdzJfr.png';
	case 95:
		return 'https://i.imgur.com/ivDj2bz.png';
	case 96:
		return 'https://i.imgur.com/1gIUNxf.png';
	case 97:
		return 'https://i.imgur.com/S9He0iU.png';
	case 98:
		return 'https://i.imgur.com/m8p99jV.png';
	case 99:
		return 'https://i.imgur.com/wpqqIaO.png';
	case 100:
		return 'https://i.imgur.com/Z7eVJ5Y.png';
	case 101:
		return 'https://i.imgur.com/0oPmFyC.png';
	case 102:
		return 'https://i.imgur.com/KyjMo8Q.png';
	case 103:
		return 'https://i.imgur.com/0jXTeY8.png';
	case 104:
		return 'https://i.imgur.com/CsCEhOy.png';
	case 105:
		return 'https://i.imgur.com/E2N3tol.png';
	case 106:
		return 'https://i.imgur.com/Sg8Bysa.png';
	case 107:
		return 'https://i.imgur.com/O6IoPG8.png';
	case 108:
		return 'https://i.imgur.com/FrXGheP.png';
	case 109:
		return 'https://i.imgur.com/PW0sa3F.png';
	case 110:
		return 'https://i.imgur.com/V0TxpIB.png';
	case 111:
		return 'https://i.imgur.com/VVvtJBF.png';
	case 112:
		return 'https://i.imgur.com/loYUcsr.png';
	case 113:
		return 'https://i.imgur.com/fzjyZpR.png';
	case 114:
		return 'https://i.imgur.com/yrIwymL.png';
	case 115:
		return 'https://i.imgur.com/PBND6JQ.png';
	case 116:
		return 'https://i.imgur.com/3i4qRFd.png';
	case 117:
		return 'https://i.imgur.com/XtVop4c.png';
	case 118:
		return 'https://i.imgur.com/JIdKeqt.png';
	case 119:
		return 'https://i.imgur.com/aZjkXGD.png';
	case 120:
		return 'https://i.imgur.com/bo2Qr00.png';
	case 121:
		return 'https://i.imgur.com/5gc3XTj.png';
	case 122:
		return 'https://i.imgur.com/ext2L1l.png';
	case 123:
		return 'https://i.imgur.com/sH79VkJ.png';
	case 124:
		return 'https://i.imgur.com/8UmBoLH.png';
	case 125:
		return 'https://i.imgur.com/iK52v6I.png';
	case 126:
		return 'https://i.imgur.com/8ym2EDy.png';
	case 127:
		return 'https://i.imgur.com/kwFT1My.png';
	case 128:
		return 'https://i.imgur.com/r9fHXOp.png';
	case 129:
		return 'https://i.imgur.com/NMgYRU6.png';
	case 130:
		return 'https://i.imgur.com/CFocQQ8.png';
	case 131:
		return 'https://i.imgur.com/TOg8AtX.png';
	case 132:
		return 'https://i.imgur.com/fe0WYLS.png';
	case 133:
		return 'https://i.imgur.com/QlSZriO.png';
	case 134:
		return 'https://i.imgur.com/ebfljvB.png';
	case 135:
		return 'https://i.imgur.com/vGi7FtB.png';
	case 136:
		return 'https://i.imgur.com/atb0TXN.png';
	case 137:
		return 'https://i.imgur.com/58UKrwj.png';
	case 138:
		return 'https://i.imgur.com/1HAiXWv.png';
	case 139:
		return 'https://i.imgur.com/td7aw4D.png';
	case 140:
		return 'https://i.imgur.com/Ch2WDJx.png';
	case 141:
		return 'https://i.imgur.com/tczQzGG.png';
	case 142:
		return 'https://i.imgur.com/XRwucnB.png';
	case 143:
		return 'https://i.imgur.com/mIut9bD.png';
	case 144:
		return 'https://i.imgur.com/1cMyndZ.png';
	case 145:
		return 'https://i.imgur.com/oZIsnu1.png';
	case 146:
		return 'https://i.imgur.com/lyTzhQC.png';
	case 147:
		return 'https://i.imgur.com/XHzJ9Nv.png';
	case 148:
		return 'https://i.imgur.com/QKXyRzg.png';
	case 149:
		return 'https://i.imgur.com/F9W0bG5.png';
	case 150:
		return 'https://i.imgur.com/FRliKXf.png';
	case 151:
		return 'https://i.imgur.com/JIVaCq9.png';
	case 152:
		return 'https://i.imgur.com/gJePgm3.png';
	case 153:
		return 'https://i.imgur.com/jbOEHIQ.png';
	case 154:
		return 'https://i.imgur.com/6Iq9rlD.png';
	case 155:
		return 'https://i.imgur.com/7vJ1OBi.png';
	case 156:
		return 'https://i.imgur.com/RqaPlHZ.png';
	case 157:
		return 'https://i.imgur.com/LBBxemD.png';
	case 158:
		return 'https://i.imgur.com/M1Frras.png';
	case 159:
		return 'https://i.imgur.com/PWm4xfz.png';
	case 160:
		return 'https://i.imgur.com/ZkY4zXF.png';
	case 161:
		return 'https://i.imgur.com/8KnUuEM.png';
	case 162:
		return 'https://i.imgur.com/1BDspvU.png';
	case 163:
		return 'https://i.imgur.com/t2rleZJ.png';
	case 164:
		return 'https://i.imgur.com/aMf0wxD.png';
	case 165:
		return 'https://i.imgur.com/d2veCjk.png';
	case 166:
		return 'https://i.imgur.com/1SGiWAm.png';
	case 167:
		return 'https://i.imgur.com/0FnonUz.png';
	case 168:
		return 'https://i.imgur.com/So3rJHG.png';
	case 169:
		return 'https://i.imgur.com/pDeke4d.png';
	case 170:
		return 'https://i.imgur.com/3aBlHTY.png';
	case 171:
		return 'https://i.imgur.com/cQFAbsE.png';
	case 172:
		return 'https://i.imgur.com/yXcZTuT.png';
	case 173:
		return 'https://i.imgur.com/i8TWhUb.png';
	case 174:
		return 'https://i.imgur.com/KL7yDBQ.png';
	case 175:
		return 'https://i.imgur.com/xoku5ou.png';
	case 176:
		return 'https://i.imgur.com/5aKAhNf.png';
	case 177:
		return 'https://i.imgur.com/nuPfPu0.png';
	case 178:
		return 'https://i.imgur.com/GDupqfi.png';
	case 179:
		return 'https://i.imgur.com/5ve3mz4.png';
	case 180:
		return 'https://i.imgur.com/KJsiCJa.png';
	case 181:
		return 'https://i.imgur.com/JpNiD89.png';
	case 182:
		return 'https://i.imgur.com/oytj2T3.png';
	case 183:
		return 'https://i.imgur.com/Y02F1BF.png';
	case 184:
		return 'https://i.imgur.com/qMsO1fF.png';
	case 185:
		return 'https://i.imgur.com/g797JIG.png';
	case 186:
		return 'https://i.imgur.com/xQiXP8Q.png';
	case 187:
		return 'https://i.imgur.com/5nBUQK6.png';
	case 188:
		return 'https://i.imgur.com/22yNal8.png';
	case 189:
		return 'https://i.imgur.com/Mcz93w8.png';
	case 190:
		return 'https://i.imgur.com/gxBt59t.png';
	case 191:
		return 'https://i.imgur.com/0hRPpxX.png';
	case 192:
		return 'https://i.imgur.com/j3CjaPI.png';
	case 193:
		return 'https://i.imgur.com/aqWlAd3.png';
	case 194:
		return 'https://i.imgur.com/65ikgW4.png';
	case 195:
		return 'https://i.imgur.com/aJTeCN9.png';
	case 196:
		return 'https://i.imgur.com/nvsm2QC.png';
	case 197:
		return 'https://i.imgur.com/xyH7uxU.png';
	case 198:
		return 'https://i.imgur.com/OVEtH0P.png';
	case 199:
		return 'https://i.imgur.com/KHMix8k.png';
	case 200:
		return 'https://i.imgur.com/YlNkOpm.png';
	case 201:
		return 'https://i.imgur.com/w99zya2.png';
	case 202:
		return 'https://i.imgur.com/2eBF7zC.png';
	case 203:
		return 'https://i.imgur.com/a55UnA9.png';
	case 204:
		return 'https://i.imgur.com/MVsnNEP.png';
	case 205:
		return 'https://i.imgur.com/oyx8pur.png';
	case 206:
		return 'https://i.imgur.com/t4ntQZ1.png';
	case 207:
		return 'https://i.imgur.com/I7T1K7b.png';
	case 208:
		return 'https://i.imgur.com/E4RiJcE.png';
	case 209:
		return 'https://i.imgur.com/I0O8t1S.png';
	case 210:
		return 'https://i.imgur.com/STUKBOv.png';
	case 211:
		return 'https://i.imgur.com/NN2JxKN.png';
	case 212:
		return 'https://i.imgur.com/Uf92K3p.png';
	case 213:
		return 'https://i.imgur.com/awBb5Ug.png';
	case 214:
		return 'https://i.imgur.com/FSFpTrn.png';
	case 215:
		return 'https://i.imgur.com/BugDJVc.png';
	case 216:
		return 'https://i.imgur.com/iw3UoGK.png';
	case 217:
		return 'https://i.imgur.com/LUOZR2M.png';
	case 218:
		return 'https://i.imgur.com/o1fRCuw.png';
	case 219:
		return 'https://i.imgur.com/kBYE3bJ.png';
	case 220:
		return 'https://i.imgur.com/jiVNOky.png';
	case 221:
		return 'https://i.imgur.com/oYB7008.png';
	case 222:
		return 'https://i.imgur.com/2cx1200.png';
	case 223:
		return 'https://i.imgur.com/7o2RNiX.png';
	case 224:
		return 'https://i.imgur.com/fV8PsOJ.png';
	case 225:
		return 'https://i.imgur.com/ileKzpw.png';
	case 226:
		return 'https://i.imgur.com/0Bb8Q64.png';
	case 227:
		return 'https://i.imgur.com/gk9HmyW.png';
	case 228:
		return 'https://i.imgur.com/qluhF5E.png';
	case 229:
		return 'https://i.imgur.com/90U760e.png';
	case 230:
		return 'https://i.imgur.com/Ni5gdRt.png';
	case 231:
		return 'https://i.imgur.com/LIw012g.png';
	case 232:
		return 'https://i.imgur.com/B5dslzw.png';
	case 233:
		return 'https://i.imgur.com/M1uLrFG.png';
	case 234:
		return 'https://i.imgur.com/xJ7Kh22.png';
	case 235:
		return 'https://i.imgur.com/VZ2vvXe.png';
	case 236:
		return 'https://i.imgur.com/EoDDe5G.png';
	case 237:
		return 'https://i.imgur.com/N2DGj0x.png';
	case 238:
		return 'https://i.imgur.com/XcdA0fG.png';
	case 239:
		return 'https://i.imgur.com/0a0uXIm.png';
	case 240:
		return 'https://i.imgur.com/0yUserz.png';
	case 241:
		return 'https://i.imgur.com/Zbto6Ey.png';
	case 242:
		return 'https://i.imgur.com/jiIGg2b.png';
	case 243:
		return 'https://i.imgur.com/VEJo4Sm.png';
	case 244:
		return 'https://i.imgur.com/1MqNVmf.png';
	case 245:
		return 'https://i.imgur.com/RcU4tOR.png';
	case 246:
		return 'https://i.imgur.com/hhbhg93.png';
	case 247:
		return 'https://i.imgur.com/Ex6jjkE.png';
	case 248:
		return 'https://i.imgur.com/ZSSdPdp.png';
	case 249:
		return 'https://i.imgur.com/wm1krLQ.png';
	case 250:
		return 'https://i.imgur.com/N7ZWxOu.png';
	case 251:
		return 'https://i.imgur.com/z8b6D2L.png';
	case 252:
		return 'https://i.imgur.com/IaySPfZ.png';
	case 253:
		return 'https://i.imgur.com/3jMopGK.png';
	case 254:
		return 'https://i.imgur.com/lEq3cPr.png';
	case 255:
		return 'https://i.imgur.com/4hEyM7w.png';
	case 256:
		return 'https://i.imgur.com/gYRJXHo.png';
	case 257:
		return 'https://i.imgur.com/6bGg4mB.png';
	case 258:
		return 'https://i.imgur.com/YKgRwEB.png';
	case 259:
		return 'https://i.imgur.com/KV2gOt9.png';
	case 260:
		return 'https://i.imgur.com/pzLoHZt.png';
	case 261:
		return 'https://i.imgur.com/KofKFCE.png';
	case 262:
		return 'https://i.imgur.com/AAcKvU0.png';
	case 263:
		return 'https://i.imgur.com/Dd1wlOD.png';
	case 264:
		return 'https://i.imgur.com/gM6JnKL.png';
	case 265:
		return 'https://i.imgur.com/KFSe9vu.png';
	case 266:
		return 'https://i.imgur.com/flQcoNC.png';
	case 267:
		return 'https://i.imgur.com/QEgPVFL.png';
	case 268:
		return 'https://i.imgur.com/bdxu9B9.png';
	case 269:
		return 'https://i.imgur.com/gBeppTE.png';
	case 270:
		return 'https://i.imgur.com/oghF3Rv.png';
	case 271:
		return 'https://i.imgur.com/DC27knq.png';
	case 272:
		return 'https://i.imgur.com/Eh8mpyZ.png';
	case 273:
		return 'https://i.imgur.com/zH3Qnd4.png';
	case 274:
		return 'https://i.imgur.com/W8BQF4L.png';
	case 275:
		return 'https://i.imgur.com/28qdsDU.png';
	case 276:
		return 'https://i.imgur.com/WlLcQ2C.png';
	case 277:
		return 'https://i.imgur.com/amSiMN4.png';
	case 278:
		return 'https://i.imgur.com/9GTzjXs.png';
	case 279:
		return 'https://i.imgur.com/2GGmezf.png';
	case 280:
		return 'https://i.imgur.com/nuM1pFq.png';
	case 281:
		return 'https://i.imgur.com/ejYNvD1.png';
	case 282:
		return 'https://i.imgur.com/7meAcAP.png';
	case 283:
		return 'https://i.imgur.com/A6YTqYK.png';
	case 284:
		return 'https://i.imgur.com/rH2m5gY.png';
	case 285:
		return 'https://i.imgur.com/pFvJmQX.png';
	case 286:
		return 'https://i.imgur.com/PsxH8qT.png';
	case 287:
		return 'https://i.imgur.com/BYhUlJP.png';
	case 288:
		return 'https://i.imgur.com/Fg1eUH9.png';
	case 289:
		return 'https://i.imgur.com/WF0KpxV.png';
	case 290:
		return 'https://i.imgur.com/ZS2Qyx3.png';
	case 291:
		return 'https://i.imgur.com/QgJ3QDq.png';
	case 292:
		return 'https://i.imgur.com/1jdUCGM.png';
	case 293:
		return 'https://i.imgur.com/I5svXf2.png';
	case 294:
		return 'https://i.imgur.com/0kVaabw.png';
	case 295:
		return 'https://i.imgur.com/3OmNBqt.png';
	case 296:
		return 'https://i.imgur.com/lwrRx9Q.png';
	case 297:
		return 'https://i.imgur.com/5hwB9Gd.png';
	case 298:
		return 'https://i.imgur.com/zjMTPBC.png';
	case 299:
		return 'https://i.imgur.com/4Ls1Irl.png';
	case 300:
		return 'https://i.imgur.com/LdMtPYT.png';
	case 301:
		return 'https://i.imgur.com/ma610en.png';
	case 302:
		return 'https://i.imgur.com/ILna7AD.png';
	case 303:
		return 'https://i.imgur.com/x3nwkd7.png';
	case 304:
		return 'https://i.imgur.com/4RMuqMz.png';
	case 305:
		return 'https://i.imgur.com/UcniWCv.png';
	case 306:
		return 'https://i.imgur.com/vRRwMjv.png';
	case 307:
		return 'https://i.imgur.com/bTJo3J4.png';
	case 308:
		return 'https://i.imgur.com/Ta4p2AZ.png';
	case 309:
		return 'https://i.imgur.com/tv5sPHT.png';
	case 310:
		return 'https://i.imgur.com/Dr5cuuc.png';
	case 311:
		return 'https://i.imgur.com/HYuUyj7.png';
	case 312:
		return 'https://i.imgur.com/mkXFCYW.png';
	case 313:
		return 'https://i.imgur.com/1bGrs5g.png';
	case 314:
		return 'https://i.imgur.com/Os7hpSl.png';
	case 315:
		return 'https://i.imgur.com/J7FxZZb.png';
	case 316:
		return 'https://i.imgur.com/vtpU3N2.png';
	case 317:
		return 'https://i.imgur.com/izRhwrt.png';
	case 318:
		return 'https://i.imgur.com/CuMFmaN.png';
	case 319:
		return 'https://i.imgur.com/p2Ys8LK.png';
	case 320:
		return 'https://i.imgur.com/NiwEvmT.png';
	case 321:
		return 'https://i.imgur.com/rQBe5pF.png';
	case 322:
		return 'https://i.imgur.com/MnFnOf2.png';
	case 323:
		return 'https://i.imgur.com/sz3dNv5.png';
	case 324:
		return 'https://i.imgur.com/ZM1ZT2V.png';
	case 325:
		return 'https://i.imgur.com/Yq6x5QO.png';
	case 326:
		return 'https://i.imgur.com/7BPrFNI.png';
	case 327:
		return 'https://i.imgur.com/RTe2kHA.png';
	case 328:
		return 'https://i.imgur.com/fiP1obo.png';
	case 329:
		return 'https://i.imgur.com/FLha1Bl.png';
	case 330:
		return 'https://i.imgur.com/DTYAYAx.png';
	case 331:
		return 'https://i.imgur.com/7CCzEDq.png';
	case 332:
		return 'https://i.imgur.com/yhl423F.png';
	case 333:
		return 'https://i.imgur.com/9iUg813.png';
	case 334:
		return 'https://i.imgur.com/7CWfSWn.png';
	case 335:
		return 'https://i.imgur.com/75A0r5o.png';
	case 336:
		return 'https://i.imgur.com/P82rZso.png';
	case 337:
		return 'https://i.imgur.com/2XC3Ouw.png';
	case 338:
		return 'https://i.imgur.com/lv1XaZh.png';
	case 339:
		return 'https://i.imgur.com/Vo9DXJQ.png';
	case 340:
		return 'https://i.imgur.com/8rGlQ5z.png';
	case 341:
		return 'https://i.imgur.com/2aZtaxi.png';
	case 342:
		return 'https://i.imgur.com/3mV5Xd1.png';
	case 343:
		return 'https://i.imgur.com/AcoXK4a.png';
	case 344:
		return 'https://i.imgur.com/u33EEZT.png';
	case 345:
		return 'https://i.imgur.com/qvsmehA.png';
	case 346:
		return 'https://i.imgur.com/595GAPI.png';
	case 347:
		return 'https://i.imgur.com/1TE6QZd.png';
	case 348:
		return 'https://i.imgur.com/WN00bKL.png';
	case 349:
		return 'https://i.imgur.com/q9hIt0p.png';
	case 350:
		return 'https://i.imgur.com/DEiBzhL.png';
	case 351:
		return 'https://i.imgur.com/QRBwtNj.png';
	case 352:
		return 'https://i.imgur.com/BwWOzri.png';
	case 353:
		return 'https://i.imgur.com/6iO89gA.png';
	case 354:
		return 'https://i.imgur.com/6Avbawx.png';
	case 355:
		return 'https://i.imgur.com/mO1kz1S.png';
	case 356:
		return 'https://i.imgur.com/WAsNJBd.png';
	case 357:
		return 'https://i.imgur.com/G1ARk7h.png';
	case 358:
		return 'https://i.imgur.com/jtCWox1.png';
	case 359:
		return 'https://i.imgur.com/zIxju0B.png';
	case 360:
		return 'https://i.imgur.com/HQSdC1c.png';
	case 361:
		return 'https://i.imgur.com/EceMu3H.png';
	case 362:
		return 'https://i.imgur.com/J0V7IVt.png';
	case 363:
		return 'https://i.imgur.com/R7Lnh87.png';
	case 364:
		return 'https://i.imgur.com/cWfitaC.png';
	case 365:
		return 'https://i.imgur.com/ChkcK1L.png';
	case 366:
		return 'https://i.imgur.com/dEqmknG.png';
	case 367:
		return 'https://i.imgur.com/bgQrJF1.png';
	case 368:
		return 'https://i.imgur.com/WF67shW.png';
	case 369:
		return 'https://i.imgur.com/K0SgvoX.png';
	case 370:
		return 'https://i.imgur.com/KF64Q1X.png';
	case 371:
		return 'https://i.imgur.com/JXmuSN8.png';
	case 372:
		return 'https://i.imgur.com/0wRa7pR.png';
	case 373:
		return 'https://i.imgur.com/YjHsDRc.png';
	case 374:
		return 'https://i.imgur.com/m1q7LTB.png';
	case 375:
		return 'https://i.imgur.com/tVlXeRw.png';
	case 376:
		return 'https://i.imgur.com/f44paOE.png';
	case 377:
		return 'https://i.imgur.com/PKTN6VB.png';
	case 378:
		return 'https://i.imgur.com/rm5wedu.png';
	case 379:
		return 'https://i.imgur.com/KksbqcN.png';
	case 380:
		return 'https://i.imgur.com/l4xX3yV.png';
	case 381:
		return 'https://i.imgur.com/ts3H84a.png';
	case 382:
		return 'https://i.imgur.com/ygLpSvU.png';
	case 383:
		return 'https://i.imgur.com/N7bkEM7.png';
	case 384:
		return 'https://i.imgur.com/VxpXCFb.png';
	case 385:
		return 'https://i.imgur.com/mSnFnhH.png';
	case 386:
		return 'https://i.imgur.com/sOBmavN.png';
	case 387:
		return 'https://i.imgur.com/FUoT0Zd.png';
	case 388:
		return 'https://i.imgur.com/zxa6e8n.png';
	case 389:
		return 'https://i.imgur.com/T4QgPnW.png';
	case 390:
		return 'https://i.imgur.com/i0pUv1Q.png';
	case 391:
		return 'https://i.imgur.com/2hkq8qI.png';
	case 392:
		return 'https://i.imgur.com/GuBgCRO.png';
	case 393:
		return 'https://i.imgur.com/PInkpug.png';
	case 394:
		return 'https://i.imgur.com/rmvA3Jj.png';
	case 395:
		return 'https://i.imgur.com/H0oQf11.png';
	case 396:
		return 'https://i.imgur.com/g245JgZ.png';
	case 397:
		return 'https://i.imgur.com/cNBN21w.png';
	case 398:
		return 'https://i.imgur.com/bEObp6Q.png';
	case 399:
		return 'https://i.imgur.com/rR58uMU.png';
	case 400:
		return 'https://i.imgur.com/3ullPX7.png';
	case 401:
		return 'https://i.imgur.com/8sGVaLp.png';
	case 402:
		return 'https://i.imgur.com/JRhDnRt.png';
	case 403:
		return 'https://i.imgur.com/qS7leYo.png';
	case 404:
		return 'https://i.imgur.com/YhHrtVE.png';
	case 405:
		return 'https://i.imgur.com/twTQQ2T.png';
	case 406:
		return 'https://i.imgur.com/0EKQWVp.png';
	case 407:
		return 'https://i.imgur.com/UMU70Em.png';
	case 408:
		return 'https://i.imgur.com/d2doiQp.png';
	case 409:
		return 'https://i.imgur.com/nM9VEnM.png';
	case 410:
		return 'https://i.imgur.com/ZibphVd.png';
	case 411:
		return 'https://i.imgur.com/DEqaV6F.png';
	case 412:
		return 'https://i.imgur.com/OMgnlyV.png';
	case 413:
		return 'https://i.imgur.com/FjKI96a.png';
	case 414:
		return 'https://i.imgur.com/pi95WdC.png';
	case 415:
		return 'https://i.imgur.com/60rgWUy.png';
	case 416:
		return 'https://i.imgur.com/IgNBwlr.png';
	case 417:
		return 'https://i.imgur.com/Il1FcJG.png';
	case 418:
		return 'https://i.imgur.com/ZZup4FH.png';
	case 419:
		return 'https://i.imgur.com/pJ40dxK.png';
	case 420:
		return 'https://i.imgur.com/yIc6Irj.png';
	case 421:
		return 'https://i.imgur.com/AVZfGzc.png';
	case 422:
		return 'https://i.imgur.com/cZIC2WX.png';
	case 423:
		return 'https://i.imgur.com/jFMvKr7.png';
	case 424:
		return 'https://i.imgur.com/tPnbpHI.png';
	case 425:
		return 'https://i.imgur.com/HRCWap1.png';
	case 426:
		return 'https://i.imgur.com/YO7mkjx.png';
	case 427:
		return 'https://i.imgur.com/YAfc2bE.png';
	case 428:
		return 'https://i.imgur.com/wHApkGY.png';
	case 429:
		return 'https://i.imgur.com/8RtqGcF.png';
	case 430:
		return 'https://i.imgur.com/Tz22SIu.png';
	case 431:
		return 'https://i.imgur.com/h7s5Bs0.png';
	case 432:
		return 'https://i.imgur.com/INZrRT0.png';
	case 433:
		return 'https://i.imgur.com/sd5EynR.png';
	case 434:
		return 'https://i.imgur.com/KYCT7YL.png';
	case 435:
		return 'https://i.imgur.com/7Yp1OOB.png';
	case 436:
		return 'https://i.imgur.com/de9EaeK.png';
	case 437:
		return 'https://i.imgur.com/Hn6hA1n.png';
	case 438:
		return 'https://i.imgur.com/fDOcqjO.png';
	case 439:
		return 'https://i.imgur.com/KPT7jcl.png';
	case 440:
		return 'https://i.imgur.com/YT7Wm0Y.png';
	case 441:
		return 'https://i.imgur.com/brKQVGj.png';
	case 442:
		return 'https://i.imgur.com/NuQCE2n.png';
	case 443:
		return 'https://i.imgur.com/qzjEMv0.png';
	case 444:
		return 'https://i.imgur.com/KL4O4LJ.png';
	case 445:
		return 'https://i.imgur.com/ijg7jps.png';
	case 446:
		return 'https://i.imgur.com/95nWT3y.png';
	case 447:
		return 'https://i.imgur.com/aev9LtA.png';
	case 448:
		return 'https://i.imgur.com/OyewEo3.png';
	case 449:
		return 'https://i.imgur.com/6qEm1b1.png';
	case 450:
		return 'https://i.imgur.com/J7P8xmW.png';
	case 451:
		return 'https://i.imgur.com/RQdl1Oq.png';
	case 452:
		return 'https://i.imgur.com/bDygLjB.png';
	case 453:
		return 'https://i.imgur.com/QiqVL9y.png';
	case 454:
		return 'https://i.imgur.com/XZryFGM.png';
	case 455:
		return 'https://i.imgur.com/aHuQEqj.png';
	case 456:
		return 'https://i.imgur.com/GceDKgE.png';
	case 457:
		return 'https://i.imgur.com/2zJJKYu.png';
	case 458:
		return 'https://i.imgur.com/Csi4TUx.png';
	case 459:
		return 'https://i.imgur.com/Upb6hin.png';
	case 460:
		return 'https://i.imgur.com/FQVUuex.png';
	case 461:
		return 'https://i.imgur.com/nv8LPZa.png';
	case 462:
		return 'https://i.imgur.com/YFdIM8X.png';
	case 463:
		return 'https://i.imgur.com/AFFsHmQ.png';
	case 464:
		return 'https://i.imgur.com/Mzc2OJ0.png';
	case 465:
		return 'https://i.imgur.com/yTQtuJG.png';
	case 466:
		return 'https://i.imgur.com/DGWghuW.png';
	case 467:
		return 'https://i.imgur.com/w7TjcBe.png';
	case 468:
		return 'https://i.imgur.com/U6bNSVw.png';
	case 469:
		return 'https://i.imgur.com/E7iUyPD.png';
	case 470:
		return 'https://i.imgur.com/2Gm9CkQ.png';
	case 471:
		return 'https://i.imgur.com/AZfwivw.png';
	case 472:
		return 'https://i.imgur.com/gYhhRGa.png';
	case 473:
		return 'https://i.imgur.com/xCljwtC.png';
	case 474:
		return 'https://i.imgur.com/zwDzqfn.png';
	case 475:
		return 'https://i.imgur.com/bD3Q8B7.png';
	case 476:
		return 'https://i.imgur.com/tWi1TYR.png';
	case 477:
		return 'https://i.imgur.com/a6dFx17.png';
	case 478:
		return 'https://i.imgur.com/VKtoTLk.png';
	case 479:
		return 'https://i.imgur.com/2wHhElC.png';
	case 480:
		return 'https://i.imgur.com/ewbPaho.png';
	case 481:
		return 'https://i.imgur.com/H723LFL.png';
	case 482:
		return 'https://i.imgur.com/vNMxHKT.png';
	case 483:
		return 'https://i.imgur.com/Wtt26EN.png';
	case 484:
		return 'https://i.imgur.com/zWjmyPv.png';
	case 485:
		return 'https://i.imgur.com/qOnpHqM.png';
	case 486:
		return 'https://i.imgur.com/HqTCx2X.png';
	case 487:
		return 'https://i.imgur.com/6sG4Emt.png';
	case 488:
		return 'https://i.imgur.com/ggdfN2l.png';
	case 489:
		return 'https://i.imgur.com/ywsTCXM.png';
	case 490:
		return 'https://i.imgur.com/y9lv5pI.png';
	case 491:
		return 'https://i.imgur.com/pb1GiK6.png';
	case 492:
		return 'https://i.imgur.com/ALKwgQ7.png';
	case 493:
		return 'https://i.imgur.com/TQsacOY.png';
	case 494:
		return 'https://i.imgur.com/uCmmDR9.png';
	case 495:
		return 'https://i.imgur.com/eFV3LmD.png';
	case 496:
		return 'https://i.imgur.com/Ert6XqR.png';
	case 497:
		return 'https://i.imgur.com/X6SiWZg.png';
	case 498:
		return 'https://i.imgur.com/Op0hGsy.png';
	case 499:
		return 'https://i.imgur.com/amTynpA.png';
	case 500:
		return 'https://i.imgur.com/9PpqbWo.png';
	case 501:
		return 'https://i.imgur.com/RhjazZr.png';
	case 502:
		return 'https://i.imgur.com/DYfzrjw.png';
	case 503:
		return 'https://i.imgur.com/t07u4mR.png';
	case 504:
		return 'https://i.imgur.com/55CKPy2.png';
	case 505:
		return 'https://i.imgur.com/P5C54TX.png';
	case 506:
		return 'https://i.imgur.com/Dewabcy.png';
	case 507:
		return 'https://i.imgur.com/hTAkbpJ.png';
	case 508:
		return 'https://i.imgur.com/eocwnw6.png';
	case 509:
		return 'https://i.imgur.com/f7NRqhD.png';
	case 510:
		return 'https://i.imgur.com/uBnMRT6.png';
	case 511:
		return 'https://i.imgur.com/eZb9mEq.png';
	case 512:
		return 'https://i.imgur.com/NbvWhTy.png';
	case 513:
		return 'https://i.imgur.com/eIjU3yv.png';
	case 514:
		return 'https://i.imgur.com/3BRcrs5.png';
	case 515:
		return 'https://i.imgur.com/pEJMRdK.png';
	case 516:
		return 'https://i.imgur.com/AO8wLkr.png';
	case 517:
		return 'https://i.imgur.com/HeT3Sig.png';
	case 518:
		return 'https://i.imgur.com/Qr6m3tI.png';
	case 519:
		return 'https://i.imgur.com/J8TpwDP.png';
	case 520:
		return 'https://i.imgur.com/b39wVVL.png';
	case 521:
		return 'https://i.imgur.com/hxZS5lG.png';
	case 522:
		return 'https://i.imgur.com/kbPOk71.png';
	case 523:
		return 'https://i.imgur.com/EhGknuz.png';
	case 524:
		return 'https://i.imgur.com/eXqEuau.png';
	case 525:
		return 'https://i.imgur.com/68wPiU5.png';
	case 526:
		return 'https://i.imgur.com/QSbOW2H.png';
	case 527:
		return 'https://i.imgur.com/BGUfpAT.png';
	case 528:
		return 'https://i.imgur.com/uk5ogv1.png';
	case 529:
		return 'https://i.imgur.com/X7bVtKT.png';
	case 530:
		return 'https://i.imgur.com/1jnXIBV.png';
	case 531:
		return 'https://i.imgur.com/iQhbs8j.png';
	case 532:
		return 'https://i.imgur.com/cmyQ4ty.png';
	case 533:
		return 'https://i.imgur.com/g9rnUAG.png';
	case 534:
		return 'https://i.imgur.com/u7Mz8Bo.png';
	case 535:
		return 'https://i.imgur.com/HGKsoPU.png';
	case 536:
		return 'https://i.imgur.com/pqzpLPJ.png';
	case 537:
		return 'https://i.imgur.com/bxLwsNZ.png';
	case 538:
		return 'https://i.imgur.com/XZ1i3Lw.png';
	case 539:
		return 'https://i.imgur.com/Co9AF9N.png';
	case 540:
		return 'https://i.imgur.com/4UyiwAR.png';
	case 541:
		return 'https://i.imgur.com/QFBsyYb.png';
	case 542:
		return 'https://i.imgur.com/A2LqWiU.png';
	case 543:
		return 'https://i.imgur.com/2QGUX3Q.png';
	case 544:
		return 'https://i.imgur.com/QjYLUyy.png';
	case 545:
		return 'https://i.imgur.com/PIqS2c7.png';
	case 546:
		return 'https://i.imgur.com/Q74gD9a.png';
	case 547:
		return 'https://i.imgur.com/r22xjxG.png';
	case 548:
		return 'https://i.imgur.com/cp8b3dl.png';
	case 549:
		return 'https://i.imgur.com/KY5tIDd.png';
	case 550:
		return 'https://i.imgur.com/t1xJKxu.png';
	case 551:
		return 'https://i.imgur.com/KxtgGyW.png';
	case 552:
		return 'https://i.imgur.com/67Ngzyy.png';
	case 553:
		return 'https://i.imgur.com/bTWPY7Z.png';
	case 554:
		return 'https://i.imgur.com/Z9lr0pY.png';
	case 555:
		return 'https://i.imgur.com/gl49vSu.png';
	case 556:
		return 'https://i.imgur.com/tdN9c8K.png';
	case 557:
		return 'https://i.imgur.com/6X9LTwe.png';
	case 558:
		return 'https://i.imgur.com/A4eVDvu.png';
	case 559:
		return 'https://i.imgur.com/yXtwl9M.png';
	case 560:
		return 'https://i.imgur.com/cpC5qpZ.png';
	case 561:
		return 'https://i.imgur.com/bKOdHXg.png';
	case 562:
		return 'https://i.imgur.com/ed2AdVl.png';
	case 563:
		return 'https://i.imgur.com/HYf9i37.png';
	case 564:
		return 'https://i.imgur.com/NTjgyIM.png';
	case 565:
		return 'https://i.imgur.com/dkEQrKS.png';
	case 566:
		return 'https://i.imgur.com/PMaGPFU.png';
	case 567:
		return 'https://i.imgur.com/IRxEqTC.png';
	case 568:
		return 'https://i.imgur.com/1c9hssr.png';
	case 569:
		return 'https://i.imgur.com/htIQU53.png';
	case 570:
		return 'https://i.imgur.com/fe4v7rW.png';
	case 571:
		return 'https://i.imgur.com/blpaSFI.png';
	case 572:
		return 'https://i.imgur.com/9Ut2m3x.png';
	case 573:
		return 'https://i.imgur.com/h8rhjJH.png';
	case 574:
		return 'https://i.imgur.com/OYmQRtU.png';
	case 575:
		return 'https://i.imgur.com/PuHt7vx.png';
	case 576:
		return 'https://i.imgur.com/z3Ty6EG.png';
	case 577:
		return 'https://i.imgur.com/kS8l8kh.png';
	case 578:
		return 'https://i.imgur.com/mRmj8bL.png';
	case 579:
		return 'https://i.imgur.com/wYHwtPL.png';
	case 580:
		return 'https://i.imgur.com/ZmIKvrf.png';
	case 581:
		return 'https://i.imgur.com/KJJ7Cf1.png';
	case 582:
		return 'https://i.imgur.com/Ab7o6Ho.png';
	case 583:
		return 'https://i.imgur.com/vbV3fGA.png';
	case 584:
		return 'https://i.imgur.com/hGAgZ2a.png';
	case 585:
		return 'https://i.imgur.com/ENZbXvI.png';
	case 586:
		return 'https://i.imgur.com/nRvwpVy.png';
	case 587:
		return 'https://i.imgur.com/TmPT3JF.png';
	case 588:
		return 'https://i.imgur.com/lMRni8l.png';
	case 589:
		return 'https://i.imgur.com/CnPTVpw.png';
	case 590:
		return 'https://i.imgur.com/kig0wTO.png';
	case 591:
		return 'https://i.imgur.com/ngbbsRZ.png';
	case 592:
		return 'https://i.imgur.com/6zqjJfB.png';
	case 593:
		return 'https://i.imgur.com/DBohKj3.png';
	case 594:
		return 'https://i.imgur.com/9KBTUT5.png';
	case 595:
		return 'https://i.imgur.com/KNqTFse.png';
	case 596:
		return 'https://i.imgur.com/mK027L6.png';
	case 597:
		return 'https://i.imgur.com/Lqf38xv.png';
	case 598:
		return 'https://i.imgur.com/Z4sPN1N.png';
	case 599:
		return 'https://i.imgur.com/dk6l1jw.png';
	case 600:
		return 'https://i.imgur.com/3f1rlmB.png';
	case 601:
		return 'https://i.imgur.com/KvF4Us2.png';
	case 602:
		return 'https://i.imgur.com/2SkL4JG.png';
	case 603:
		return 'https://i.imgur.com/Qt3LEvj.png';
	case 604:
		return 'https://i.imgur.com/XCxKG6M.png';
	case 605:
		return 'https://i.imgur.com/QsYxcE9.png';
	case 606:
		return 'https://i.imgur.com/53zct2j.png';
	case 607:
		return 'https://i.imgur.com/akpAssE.png';
	case 608:
		return 'https://i.imgur.com/GdpYCOC.png';
	case 609:
		return 'https://i.imgur.com/buRFkm3.png';
	case 610:
		return 'https://i.imgur.com/RBoLSCa.png';
	case 611:
		return 'https://i.imgur.com/vWYGpNs.png';
	case 612:
		return 'https://i.imgur.com/1si0Igk.png';
	case 613:
		return 'https://i.imgur.com/sy3iqPX.png';
	case 614:
		return 'https://i.imgur.com/1wY2YDY.png';
	case 615:
		return 'https://i.imgur.com/aozrqUL.png';
	case 616:
		return 'https://i.imgur.com/mnmijrC.png';
	case 617:
		return 'https://i.imgur.com/7smQfhI.png';
	case 618:
		return 'https://i.imgur.com/0UU849n.png';
	case 619:
		return 'https://i.imgur.com/CBthCUz.png';
	case 620:
		return 'https://i.imgur.com/oRplOrf.png';
	case 621:
		return 'https://i.imgur.com/uRMJ9E2.png';
	case 622:
		return 'https://i.imgur.com/9STqaoB.png';
	case 623:
		return 'https://i.imgur.com/AcAjDuo.png';
	case 624:
		return 'https://i.imgur.com/FfeeOsh.png';
	case 625:
		return 'https://i.imgur.com/CG8r3Qx.png';
	case 626:
		return 'https://i.imgur.com/4hLOuic.png';
	case 627:
		return 'https://i.imgur.com/CistWj1.png';
	case 628:
		return 'https://i.imgur.com/cD3kZIF.png';
	case 629:
		return 'https://i.imgur.com/rsUJRKh.png';
	case 630:
		return 'https://i.imgur.com/87YT050.png';
	case 631:
		return 'https://i.imgur.com/ktYd14u.png';
	case 632:
		return 'https://i.imgur.com/fRX2Vta.png';
	case 633:
		return 'https://i.imgur.com/GYxBZY4.png';
	case 634:
		return 'https://i.imgur.com/8RRQMK1.png';
	case 635:
		return 'https://i.imgur.com/D22M92v.png';
	case 636:
		return 'https://i.imgur.com/Use1NnL.png';
	case 637:
		return 'https://i.imgur.com/agsCkdA.png';
	case 638:
		return 'https://i.imgur.com/fJo1evK.png';
	case 639:
		return 'https://i.imgur.com/RK4qtcD.png';
	case 640:
		return 'https://i.imgur.com/SXVlYKi.png';
	case 641:
		return 'https://i.imgur.com/9S26NkP.png';
	case 642:
		return 'https://i.imgur.com/8JZBjRC.png';
	case 643:
		return 'https://i.imgur.com/jkQWXpv.png';
	case 644:
		return 'https://i.imgur.com/HPb5YUR.png';
	case 645:
		return 'https://i.imgur.com/HlkVcgQ.png';
	case 646:
		return 'https://i.imgur.com/drsIQTV.png';
	case 647:
		return 'https://i.imgur.com/0v10W8p.png';
	case 648:
		return 'https://i.imgur.com/dJ6jiTL.png';
	case 649:
		return 'https://i.imgur.com/iBDFrQW.png';
	case 650:
		return 'https://i.imgur.com/eoow7pi.png';
	case 651:
		return 'https://i.imgur.com/Ad4UbVK.png';
	case 652:
		return 'https://i.imgur.com/4MCuTsv.png';
	case 653:
		return 'https://i.imgur.com/1dAryzt.png';
	case 654:
		return 'https://i.imgur.com/M5Yab81.png';
	case 655:
		return 'https://i.imgur.com/YfJlyjE.png';
	case 656:
		return 'https://i.imgur.com/MNT9XQb.png';
	case 657:
		return 'https://i.imgur.com/HR7M4z9.png';
	case 658:
		return 'https://i.imgur.com/0sVNhdp.png';
	case 659:
		return 'https://i.imgur.com/LO4aLVr.png';
	case 660:
		return 'https://i.imgur.com/sftOtF4.png';
	case 661:
		return 'https://i.imgur.com/LxfivZU.png';
	case 662:
		return 'https://i.imgur.com/FzmTZYw.png';
	case 663:
		return 'https://i.imgur.com/KQpygHa.png';
	case 664:
		return 'https://i.imgur.com/1AOQ5jB.png';
	case 665:
		return 'https://i.imgur.com/y4bqm7X.png';
	case 666:
		return 'https://i.imgur.com/CiBccLx.png';
	case 667:
		return 'https://i.imgur.com/g5UsnSg.png';
	case 668:
		return 'https://i.imgur.com/Em2Mdmq.png';
	case 669:
		return 'https://i.imgur.com/TeNzfGv.png';
	case 670:
		return 'https://i.imgur.com/8QxxZQh.png';
	case 671:
		return 'https://i.imgur.com/LSPwid1.png';
	case 672:
		return 'https://i.imgur.com/Djn8dB3.png';
	case 673:
		return 'https://i.imgur.com/UqIcu9K.png';
	case 674:
		return 'https://i.imgur.com/wdT4G1C.png';
	case 675:
		return 'https://i.imgur.com/vtoB2wK.png';
	case 676:
		return 'https://i.imgur.com/oMRYG90.png';
	case 677:
		return 'https://i.imgur.com/OK7vQPD.png';
	case 678:
		return 'https://i.imgur.com/TAZB7h1.png';
	case 679:
		return 'https://i.imgur.com/HLOXoLx.png';
	case 680:
		return 'https://i.imgur.com/cyePxuf.png';
	case 681:
		return 'https://i.imgur.com/21a7IJe.png';
	case 682:
		return 'https://i.imgur.com/Bh9J4wk.png';
	case 683:
		return 'https://i.imgur.com/8ZSDTQw.png';
	case 684:
		return 'https://i.imgur.com/OjUCTCy.png';
	case 685:
		return 'https://i.imgur.com/Tozms4E.png';
	case 686:
		return 'https://i.imgur.com/nm2DTW3.png';
	case 687:
		return 'https://i.imgur.com/L9k7XJx.png';
	case 688:
		return 'https://i.imgur.com/VpuFuwq.png';
	case 689:
		return 'https://i.imgur.com/kwxx4Ou.png';
	case 690:
		return 'https://i.imgur.com/9MclUhP.png';
	case 691:
		return 'https://i.imgur.com/3qWLx7P.png';
	case 692:
		return 'https://i.imgur.com/rWOznZa.png';
	case 693:
		return 'https://i.imgur.com/Fed9hF0.png';
	case 694:
		return 'https://i.imgur.com/IuU2EPM.png';
	case 695:
		return 'https://i.imgur.com/pE3UCZN.png';
	case 696:
		return 'https://i.imgur.com/PQTuDRX.png';
	case 697:
		return 'https://i.imgur.com/cx6F81I.png';
	case 698:
		return 'https://i.imgur.com/T2oMK5x.png';
	case 699:
		return 'https://i.imgur.com/dizve9C.png';
	case 700:
		return 'https://i.imgur.com/lAwTde9.png';
	case 701:
		return 'https://i.imgur.com/uTe7Fyc.png';
	case 702:
		return 'https://i.imgur.com/raBqM6E.png';
	case 703:
		return 'https://i.imgur.com/HHaIyd5.png';
	case 704:
		return 'https://i.imgur.com/qJvyIXW.png';
	case 705:
		return 'https://i.imgur.com/zWancZH.png';
	case 706:
		return 'https://i.imgur.com/63OzZse.png';
	case 707:
		return 'https://i.imgur.com/wXBiBqa.png';
	case 708:
		return 'https://i.imgur.com/P0221Ue.png';
	case 709:
		return 'https://i.imgur.com/MJEH7gl.png';
	case 710:
		return 'https://i.imgur.com/lTPIj8Z.png';
	case 711:
		return 'https://i.imgur.com/GjZkKXZ.png';
	case 712:
		return 'https://i.imgur.com/u4ZzQnG.png';
	case 713:
		return 'https://i.imgur.com/1lxwjWy.png';
	case 714:
		return 'https://i.imgur.com/IThP87K.png';
	case 715:
		return 'https://i.imgur.com/AVXTnIb.png';
	case 716:
		return 'https://i.imgur.com/b3khMcT.png';
	case 717:
		return 'https://i.imgur.com/tlPPmxB.png';
	case 718:
		return 'https://i.imgur.com/TWTluwF.png';
	case 719:
		return 'https://i.imgur.com/CcFdJf0.png';
	case 720:
		return 'https://i.imgur.com/MQoxb7I.png';
	case 721:
		return 'https://i.imgur.com/Tl6b8ZP.png';
	case 722:
		return 'https://i.imgur.com/y23auhM.png';
	case 723:
		return 'https://i.imgur.com/vOS6D58.png';
	case 724:
		return 'https://i.imgur.com/Y733y3P.png';
	case 725:
		return 'https://i.imgur.com/ZDNTm2Q.png';
	case 726:
		return 'https://i.imgur.com/SwD0a9m.png';
	case 727:
		return 'https://i.imgur.com/FohVEVa.png';
	case 728:
		return 'https://i.imgur.com/ECxGSl6.png';
	case 729:
		return 'https://i.imgur.com/Iz48jiB.png';
	case 730:
		return 'https://i.imgur.com/hBmupIk.png';
	case 731:
		return 'https://i.imgur.com/4XES91G.png';
	case 732:
		return 'https://i.imgur.com/0Bmfk4I.png';
	case 733:
		return 'https://i.imgur.com/ggJvwsV.png';
	case 734:
		return 'https://i.imgur.com/udMgkrh.png';
	case 735:
		return 'https://i.imgur.com/xQMrvxD.png';
	case 736:
		return 'https://i.imgur.com/vg4idZQ.png';
	case 737:
		return 'https://i.imgur.com/zG77VG0.png';
	case 738:
		return 'https://i.imgur.com/LkhMEW3.png';
	case 739:
		return 'https://i.imgur.com/dIbk0rX.png';
	case 740:
		return 'https://i.imgur.com/9JGJ5b5.png';
	case 741:
		return 'https://i.imgur.com/D7MiYsT.png';
	case 742:
		return 'https://i.imgur.com/o4NOc2P.png';
	case 743:
		return 'https://i.imgur.com/gAzwriU.png';
	case 744:
		return 'https://i.imgur.com/IR6Lifk.png';
	case 745:
		return 'https://i.imgur.com/ZwxebNY.png';
	case 746:
		return 'https://i.imgur.com/3FrWECe.png';
	case 747:
		return 'https://i.imgur.com/ssCyN45.png';
	case 748:
		return 'https://i.imgur.com/4oAEBmC.png';
	case 749:
		return 'https://i.imgur.com/Bwfs32k.png';
	case 750:
		return 'https://i.imgur.com/XriSJHE.png';
	case 751:
		return 'https://i.imgur.com/oil0A1d.png';
	case 752:
		return 'https://i.imgur.com/5RHvRo8.png';
	case 753:
		return 'https://i.imgur.com/HBDBBoT.png';
	case 754:
		return 'https://i.imgur.com/VTegfc1.png';
	case 755:
		return 'https://i.imgur.com/vfUsOsR.png';
	case 756:
		return 'https://i.imgur.com/DrLSTvO.png';
	case 757:
		return 'https://i.imgur.com/lgaYAfZ.png';
	case 758:
		return 'https://i.imgur.com/BTL0AEW.png';
	case 759:
		return 'https://i.imgur.com/3G2cdsC.png';
	case 760:
		return 'https://i.imgur.com/7minNHT.png';
	case 761:
		return 'https://i.imgur.com/rtV618l.png';
	case 762:
		return 'https://i.imgur.com/cfzZ2H2.png';
	case 763:
		return 'https://i.imgur.com/14bbgcJ.png';
	case 764:
		return 'https://i.imgur.com/jtLgOZd.png';
	case 765:
		return 'https://i.imgur.com/luX66A5.png';
	case 766:
		return 'https://i.imgur.com/KIrP6Bq.png';
	case 767:
		return 'https://i.imgur.com/kNq3TCp.png';
	case 768:
		return 'https://i.imgur.com/IU1vZw3.png';
	case 769:
		return 'https://i.imgur.com/jcXpkZy.png';
	case 770:
		return 'https://i.imgur.com/DiPApDd.png';
	case 771:
		return 'https://i.imgur.com/PsjbUVE.png';
	case 772:
		return 'https://i.imgur.com/MHTllXp.png';
	case 773:
		return 'https://i.imgur.com/8ZF0g5n.png';
	case 774:
		return 'https://i.imgur.com/qNw7EVG.png';
	case 775:
		return 'https://i.imgur.com/gkI0rxQ.png';
	case 776:
		return 'https://i.imgur.com/SY0zKJX.png';
	case 777:
		return 'https://i.imgur.com/dtNOzNf.png';
	case 778:
		return 'https://i.imgur.com/kd6LQ6Q.png';
	case 779:
		return 'https://i.imgur.com/S4FvFgv.png';
	case 780:
		return 'https://i.imgur.com/1uX2XRV.png';
	case 781:
		return 'https://i.imgur.com/W47ob2C.png';
	case 782:
		return 'https://i.imgur.com/4aRxZ92.png';
	case 783:
		return 'https://i.imgur.com/rGNdL7O.png';
	case 784:
		return 'https://i.imgur.com/rdZjcT7.png';
	case 785:
		return 'https://i.imgur.com/IezC7fJ.png';
	case 786:
		return 'https://i.imgur.com/a4N0eIh.png';
	case 787:
		return 'https://i.imgur.com/1B6U3sZ.png';
	case 788:
		return 'https://i.imgur.com/G0zW3ix.png';
	case 789:
		return 'https://i.imgur.com/umAosON.png';
	case 790:
		return 'https://i.imgur.com/0uuoaSS.png';
	case 791:
		return 'https://i.imgur.com/b56Rhgt.png';
	case 792:
		return 'https://i.imgur.com/GJCIy6D.png';
	case 793:
		return 'https://i.imgur.com/uW8WJ3W.png';
	case 794:
		return 'https://i.imgur.com/BNPJwH8.png';
	case 795:
		return 'https://i.imgur.com/Uf05dF3.png';
	case 796:
		return 'https://i.imgur.com/LwrMRwp.png';
	case 797:
		return 'https://i.imgur.com/SyKbOR7.png';
	case 798:
		return 'https://i.imgur.com/OCuDNEC.png';
	case 799:
		return 'https://i.imgur.com/rRdbXc1.png';
	case 800:
		return 'https://i.imgur.com/YM6yD4r.png';
	case 801:
		return 'https://i.imgur.com/1PKeI0U.png';
	case 802:
		return 'https://i.imgur.com/f5RE3oE.png';
	case 803:
		return 'https://i.imgur.com/GpM408d.png';
	case 804:
		return 'https://i.imgur.com/WN1TWmd.png';
	case 805:
		return 'https://i.imgur.com/plu61hX.png';
	case 806:
		return 'https://i.imgur.com/rjTGRL8.png';
	case 807:
		return 'https://i.imgur.com/U3K5Nu0.png';
	case 808:
		return 'https://i.imgur.com/PaxmVJe.png';
	case 809:
		return 'https://i.imgur.com/19cWRWO.png';
	case 810:
		return 'https://i.imgur.com/tunh9am.png';
	case 811:
		return 'https://i.imgur.com/ygXf8Ki.png';
	case 812:
		return 'https://i.imgur.com/KYU7euu.png';
	case 813:
		return 'https://i.imgur.com/3sxYYAn.png';
	case 814:
		return 'https://i.imgur.com/CnaQp4g.png';
	case 815:
		return 'https://i.imgur.com/9IEEGHf.png';
	case 816:
		return 'https://i.imgur.com/FHnDWUp.png';
	case 817:
		return 'https://i.imgur.com/BqRHQ0h.png';
	case 818:
		return 'https://i.imgur.com/EhEc4si.png';
	case 819:
		return 'https://i.imgur.com/dE4xzEF.png';
	case 820:
		return 'https://i.imgur.com/CD9kd3Z.png';
	case 821:
		return 'https://i.imgur.com/PcymMNJ.png';
	case 822:
		return 'https://i.imgur.com/LBs8Ibf.png';
	case 823:
		return 'https://i.imgur.com/st5VH6i.png';
	case 824:
		return 'https://i.imgur.com/VLepGI6.png';
	case 825:
		return 'https://i.imgur.com/TPNJVSj.png';
	case 826:
		return 'https://i.imgur.com/j7lTJav.png';
	case 827:
		return 'https://i.imgur.com/GnWYp3k.png';
	case 828:
		return 'https://i.imgur.com/adMihL4.png';
	case 829:
		return 'https://i.imgur.com/wP9Sddo.png';
	case 830:
		return 'https://i.imgur.com/Vxt5Hok.png';
	case 831:
		return 'https://i.imgur.com/T5E1PzC.png';
	case 832:
		return 'https://i.imgur.com/fcI2q29.png';
	case 833:
		return 'https://i.imgur.com/bUFIQ70.png';
	case 834:
		return 'https://i.imgur.com/j6K7acH.png';
	case 835:
		return 'https://i.imgur.com/8KVlzkh.png';
	case 836:
		return 'https://i.imgur.com/p3AYZBo.png';
	case 837:
		return 'https://i.imgur.com/4qzwr0O.png';
	case 838:
		return 'https://i.imgur.com/hg0uZ17.png';
	case 839:
		return 'https://i.imgur.com/vTRPl1s.png';
	case 840:
		return 'https://i.imgur.com/DJC7uHI.png';
	case 841:
		return 'https://i.imgur.com/NV3XzvJ.png';
	case 842:
		return 'https://i.imgur.com/rS3S7i5.png';
	case 843:
		return 'https://i.imgur.com/t8CzGv1.png';
	case 844:
		return 'https://i.imgur.com/4gbRh9l.png';
	case 845:
		return 'https://i.imgur.com/ii3mAIK.png';
	case 846:
		return 'https://i.imgur.com/FqUFu02.png';
	case 847:
		return 'https://i.imgur.com/yUmzjb4.png';
	case 848:
		return 'https://i.imgur.com/lAWzj0P.png';
	case 849:
		return 'https://i.imgur.com/jsg5eay.png';
	case 850:
		return 'https://i.imgur.com/2jpdwZN.png';
	case 851:
		return 'https://i.imgur.com/yi0wfgT.png';
	case 852:
		return 'https://i.imgur.com/cxKieEc.png';
	case 853:
		return 'https://i.imgur.com/MumGjNa.png';
	case 854:
		return 'https://i.imgur.com/G7lxP1u.png';
	case 855:
		return 'https://i.imgur.com/0S2ILHY.png';
	case 856:
		return 'https://i.imgur.com/uO1nttE.png';
	case 857:
		return 'https://i.imgur.com/6JrYSNo.png';
	case 858:
		return 'https://i.imgur.com/Um4YOCC.png';
	case 859:
		return 'https://i.imgur.com/9HBexMU.png';
	case 860:
		return 'https://i.imgur.com/oYyWD41.png';
	case 861:
		return 'https://i.imgur.com/RY1Jvdw.png';
	case 862:
		return 'https://i.imgur.com/BhIHHOj.png';
	case 863:
		return 'https://i.imgur.com/6MDmFa0.png';
	case 864:
		return 'https://i.imgur.com/rXKuy5N.png';
	case 865:
		return 'https://i.imgur.com/LT7yhkm.png';
	case 866:
		return 'https://i.imgur.com/FaP4np4.png';
	case 867:
		return 'https://i.imgur.com/ChWJd4x.png';
	case 868:
		return 'https://i.imgur.com/o3MfWvT.png';
	case 869:
		return 'https://i.imgur.com/mjoVVpv.png';
	case 870:
		return 'https://i.imgur.com/vsy6OJT.png';
	case 871:
		return 'https://i.imgur.com/TdRj7S5.png';
	case 872:
		return 'https://i.imgur.com/d3UuN0g.png';
	case 873:
		return 'https://i.imgur.com/AhsUvXW.png';
	case 874:
		return 'https://i.imgur.com/ukHjwxY.png';
	case 875:
		return 'https://i.imgur.com/EdhDjTQ.png';
	case 876:
		return 'https://i.imgur.com/ucLzEiG.png';
	case 877:
		return 'https://i.imgur.com/yiNaWYr.png';
	case 878:
		return 'https://i.imgur.com/zlHoglw.png';
	case 879:
		return 'https://i.imgur.com/b0OY9gr.png';
	case 880:
		return 'https://i.imgur.com/d1tYr8I.png';
	case 881:
		return 'https://i.imgur.com/BWhrlCr.png';
	case 882:
		return 'https://i.imgur.com/upxoBPY.png';
	case 883:
		return 'https://i.imgur.com/G2OPqxn.png';
	case 884:
		return 'https://i.imgur.com/aa8y1Rp.png';
	case 885:
		return 'https://i.imgur.com/4fUZDzU.png';
	case 886:
		return 'https://i.imgur.com/S78zPFb.png';
	case 887:
		return 'https://i.imgur.com/8yZPxDC.png';
	case 888:
		return 'https://i.imgur.com/Ilf3E0Z.png';
	case 889:
		return 'https://i.imgur.com/Qvqhzm5.png';
	case 890:
		return 'https://i.imgur.com/UNq9TIi.png';
	case 891:
		return 'https://i.imgur.com/dIBbrUr.png';
	case 892:
		return 'https://i.imgur.com/VUIxSon.png';
	case 893:
		return 'https://i.imgur.com/k72b3HQ.png';
	case 894:
		return 'https://i.imgur.com/BWrHivc.png';
	case 895:
		return 'https://i.imgur.com/C3alU7l.png';
	case 896:
		return 'https://i.imgur.com/hd2OCB9.png';
	case 897:
		return 'https://i.imgur.com/UyfIZmp.png';
	case 898:
		return 'https://i.imgur.com/8bgTcwj.png';
	case 899:
		return 'https://i.imgur.com/ZkeN3Hj.png';
	case 900:
		return 'https://i.imgur.com/2TetyOv.png';
	case 901:
		return 'https://i.imgur.com/YrengjX.png';
	case 902:
		return 'https://i.imgur.com/04yNeG9.png';
	case 903:
		return 'https://i.imgur.com/GUjMnJ5.png';
	case 904:
		return 'https://i.imgur.com/aDET8ia.png';
	case 905:
		return 'https://i.imgur.com/JBvHC6d.png';
	case 906:
		return 'https://i.imgur.com/uQjuwkJ.png';
	case 907:
		return 'https://i.imgur.com/SSypC0B.png';
	case 908:
		return 'https://i.imgur.com/GT5NEyi.png';
	case 909:
		return 'https://i.imgur.com/1sCOiE9.png';
	case 910:
		return 'https://i.imgur.com/krkE5Fk.png';
	case 911:
		return 'https://i.imgur.com/aWUQGT1.png';
	case 912:
		return 'https://i.imgur.com/mZeZQbn.png';
	case 913:
		return 'https://i.imgur.com/TMzVZUH.png';
	case 914:
		return 'https://i.imgur.com/IDv9mPV.png';
	case 915:
		return 'https://i.imgur.com/qYm0O5k.png';
	case 916:
		return 'https://i.imgur.com/k4Mqk8y.png';
	case 917:
		return 'https://i.imgur.com/NHHQ33h.png';
	case 918:
		return 'https://i.imgur.com/woGovBM.png';
	case 919:
		return 'https://i.imgur.com/Eg3l7bN.png';
	case 920:
		return 'https://i.imgur.com/TmeJ5U2.png';
	case 921:
		return 'https://i.imgur.com/k5Lg3rn.png';
	case 922:
		return 'https://i.imgur.com/WdYpQj4.png';
	case 923:
		return 'https://i.imgur.com/QzA7uD4.png';
	case 924:
		return 'https://i.imgur.com/H5eBnT4.png';
	case 925:
		return 'https://i.imgur.com/f3sY3Cj.png';
	case 926:
		return 'https://i.imgur.com/Aa82rXg.png';
	case 927:
		return 'https://i.imgur.com/xVkiiJq.png';
	case 928:
		return 'https://i.imgur.com/7YoGbNC.png';
	case 929:
		return 'https://i.imgur.com/qvlO05Q.png';
	case 930:
		return 'https://i.imgur.com/fBdvYo9.png';
	case 931:
		return 'https://i.imgur.com/QqXs1Ah.png';
	case 932:
		return 'https://i.imgur.com/VD5P70D.png';
	case 933:
		return 'https://i.imgur.com/winDeOB.png';
	case 934:
		return 'https://i.imgur.com/u0Vr0xj.png';
	case 935:
		return 'https://i.imgur.com/5ei61Ha.png';
	case 936:
		return 'https://i.imgur.com/QRRZzoM.png';
	case 937:
		return 'https://i.imgur.com/52juEYv.png';
	case 938:
		return 'https://i.imgur.com/vmPq36J.png';
	case 939:
		return 'https://i.imgur.com/gzMksEi.png';
	case 940:
		return 'https://i.imgur.com/HU1vAC2.png';
	case 941:
		return 'https://i.imgur.com/jyhskXn.png';
	case 942:
		return 'https://i.imgur.com/9CZ4cJU.png';
	case 943:
		return 'https://i.imgur.com/lgO8ARJ.png';
	case 944:
		return 'https://i.imgur.com/CfT5OL7.png';
	case 945:
		return 'https://i.imgur.com/NkfF9rE.png';
	case 946:
		return 'https://i.imgur.com/u0zrNIr.png';
	case 947:
		return 'https://i.imgur.com/gN5zTHS.png';
	case 948:
		return 'https://i.imgur.com/UUtykE9.png';
	case 949:
		return 'https://i.imgur.com/Z8CsPqL.png';
	case 950:
		return 'https://i.imgur.com/qyMfV75.png';
	case 951:
		return 'https://i.imgur.com/vPW0enr.png';
	case 952:
		return 'https://i.imgur.com/K86YZV3.png';
	case 953:
		return 'https://i.imgur.com/u4eYGts.png';
	case 954:
		return 'https://i.imgur.com/4vT7qZP.png';
	case 955:
		return 'https://i.imgur.com/W75RL6s.png';
	case 956:
		return 'https://i.imgur.com/3Ujv1Xs.png';
	case 957:
		return 'https://i.imgur.com/peAaFTI.png';
	case 958:
		return 'https://i.imgur.com/zcBDQkx.png';
	case 959:
		return 'https://i.imgur.com/doEckP8.png';
	case 960:
		return 'https://i.imgur.com/rYMEngI.png';
	case 961:
		return 'https://i.imgur.com/95pcx03.png';
	case 962:
		return 'https://i.imgur.com/u0kHpww.png';
	case 963:
		return 'https://i.imgur.com/c2vEWX9.png';
	case 964:
		return 'https://i.imgur.com/9yGDHss.png';
	case 965:
		return 'https://i.imgur.com/uzhmzNW.png';
	case 966:
		return 'https://i.imgur.com/MEO9GyP.png';
	case 967:
		return 'https://i.imgur.com/rHlXXCm.png';
	case 968:
		return 'https://i.imgur.com/Z5hP4aV.png';
	case 969:
		return 'https://i.imgur.com/MPzvQAF.png';
	case 970:
		return 'https://i.imgur.com/0Zb6E90.png';
	case 971:
		return 'https://i.imgur.com/wUTElSx.png';
	case 972:
		return 'https://i.imgur.com/IFMfo2b.png';
	case 973:
		return 'https://i.imgur.com/LsISWpT.png';
	case 974:
		return 'https://i.imgur.com/LIoMQB1.png';
	case 975:
		return 'https://i.imgur.com/LEj83vO.png';
	case 976:
		return 'https://i.imgur.com/qH9Budy.png';
	case 977:
		return 'https://i.imgur.com/9VZ3Elp.png';
	case 978:
		return 'https://i.imgur.com/DpwUvLh.png';
	case 979:
		return 'https://i.imgur.com/AQWPo6b.png';
	case 980:
		return 'https://i.imgur.com/F9Bceil.png';
	case 981:
		return 'https://i.imgur.com/vWtZi2p.png';
	case 982:
		return 'https://i.imgur.com/ferHDcE.png';
	case 983:
		return 'https://i.imgur.com/0VpGSXe.png';
	case 984:
		return 'https://i.imgur.com/HJp56VO.png';
	case 985:
		return 'https://i.imgur.com/pRnfYxP.png';
	case 986:
		return 'https://i.imgur.com/FCFO0z3.png';
	case 987:
		return 'https://i.imgur.com/UL9P7DU.png';
	case 988:
		return 'https://i.imgur.com/5rjY4vx.png';
	case 989:
		return 'https://i.imgur.com/s01YP8Z.png';
	}
}

function randomSwitchHub(ran) {
	switch(ran) {
	case 1: {
		const ranNum = Math.floor(Math.random() * (989 - 1) + 1);

		return findImage(ranNum);
	}
	case 2: {
		const ranNum = Math.floor(Math.random() * (60 - 1) + 1);

		return findBocchi(ranNum);
	}
	case 3: {
		const ranNum = Math.floor(Math.random() * (353 - 1) + 1);

		return findImas(ranNum);
	}
	}
}

function findImas(ran) {
	switch(ran) {
	case 1:
		return 'https://i.imgur.com/uiVLHtS.png';
	case 2:
		return 'https://i.imgur.com/RR6jU6y.png';
	case 3:
		return 'https://i.imgur.com/fHAGT5v.png';
	case 4:
		return 'https://i.imgur.com/d29A0eo.png';
	case 5:
		return 'https://i.imgur.com/ZoVH6Zz.png';
	case 6:
		return 'https://i.imgur.com/aFzmwDP.png';
	case 7:
		return 'https://i.imgur.com/gmmQ4J8.png';
	case 8:
		return 'https://i.imgur.com/tngGb6t.png';
	case 9:
		return 'https://i.imgur.com/qiQMUTW.png';
	case 10:
		return 'https://i.imgur.com/x1CpT8y.png';
	case 11:
		return 'https://i.imgur.com/f5zaZEJ.png';
	case 12:
		return 'https://i.imgur.com/wWiilX8.png';
	case 13:
		return 'https://i.imgur.com/CRgYHYE.png';
	case 14:
		return 'https://i.imgur.com/khFXuzI.png';
	case 15:
		return 'https://i.imgur.com/5HJ9lEt.png';
	case 16:
		return 'https://i.imgur.com/bR1U2g2.png';
	case 17:
		return 'https://i.imgur.com/dKxHVdm.png';
	case 18:
		return 'https://i.imgur.com/6rQKkel.png';
	case 19:
		return 'https://i.imgur.com/JdcHGPm.png';
	case 20:
		return 'https://i.imgur.com/TpOg5cJ.png';
	case 21:
		return 'https://i.imgur.com/HZSlZ6o.png';
	case 22:
		return 'https://i.imgur.com/r8VPYll.png';
	case 23:
		return 'https://i.imgur.com/IHeOUGw.png';
	case 24:
		return 'https://i.imgur.com/dz5b2Ni.png';
	case 25:
		return 'https://i.imgur.com/ikwnbxc.png';
	case 26:
		return 'https://i.imgur.com/QI1LgbI.png';
	case 27:
		return 'https://i.imgur.com/N9f00oG.png';
	case 28:
		return 'https://i.imgur.com/uIWveLM.png';
	case 29:
		return 'https://i.imgur.com/ghjNRaB.png';
	case 30:
		return 'https://i.imgur.com/OcGWyz6.png';
	case 31:
		return 'https://i.imgur.com/rWMsyh7.png';
	case 32:
		return 'https://i.imgur.com/0rlBMMZ.png';
	case 33:
		return 'https://i.imgur.com/gFUUFvo.png';
	case 34:
		return 'https://i.imgur.com/aAi23nG.png';
	case 35:
		return 'https://i.imgur.com/CkUnHxu.png';
	case 36:
		return 'https://i.imgur.com/YxdT76d.png';
	case 37:
		return 'https://i.imgur.com/K8dDm5s.png';
	case 38:
		return 'https://i.imgur.com/MVLrl5V.png';
	case 39:
		return 'https://i.imgur.com/ZsHoYmP.png';
	case 40:
		return 'https://i.imgur.com/Y2hlKio.png';
	case 41:
		return 'https://i.imgur.com/ftqprXI.png';
	case 42:
		return 'https://i.imgur.com/6Uzr0L6.png';
	case 43:
		return 'https://i.imgur.com/GZhH9tq.png';
	case 44:
		return 'https://i.imgur.com/xybYbZ6.png';
	case 45:
		return 'https://i.imgur.com/x4l7VvU.png';
	case 46:
		return 'https://i.imgur.com/kiqdbsZ.png';
	case 47:
		return 'https://i.imgur.com/7FEfRuf.png';
	case 48:
		return 'https://i.imgur.com/YXR4adc.png';
	case 49:
		return 'https://i.imgur.com/d3cbbh3.png';
	case 50:
		return 'https://i.imgur.com/OFEBx7F.png';
	case 51:
		return 'https://i.imgur.com/LUkdUwi.png';
	case 52:
		return 'https://i.imgur.com/SZ8Mqi0.png';
	case 53:
		return 'https://i.imgur.com/HcPSm6n.png';
	case 54:
		return 'https://i.imgur.com/9APlkFZ.png';
	case 55:
		return 'https://i.imgur.com/usdphgm.png';
	case 56:
		return 'https://i.imgur.com/10tMEIh.png';
	case 57:
		return 'https://i.imgur.com/QOsTDI5.png';
	case 58:
		return 'https://i.imgur.com/nlGXo6J.png';
	case 59:
		return 'https://i.imgur.com/W52Tsgk.png';
	case 60:
		return 'https://i.imgur.com/T0ubpjV.png';
	case 61:
		return 'https://i.imgur.com/r2pWg7s.png';
	case 62:
		return 'https://i.imgur.com/yOw4KQZ.png';
	case 63:
		return 'https://i.imgur.com/F8Fsq2O.png';
	case 64:
		return 'https://i.imgur.com/s6iQBFS.png';
	case 65:
		return 'https://i.imgur.com/KxNEFPl.png';
	case 66:
		return 'https://i.imgur.com/XeM9DiJ.png';
	case 67:
		return 'https://i.imgur.com/Bf8I9We.png';
	case 68:
		return 'https://i.imgur.com/5KzUehb.png';
	case 69:
		return 'https://i.imgur.com/JeTP0Xm.png';
	case 70:
		return 'https://i.imgur.com/IAWj2hZ.png';
	case 71:
		return 'https://i.imgur.com/Va2ORzk.png';
	case 72:
		return 'https://i.imgur.com/GF0YaxZ.png';
	case 73:
		return 'https://i.imgur.com/ESTUtZM.png';
	case 74:
		return 'https://i.imgur.com/TjQOb6j.png';
	case 75:
		return 'https://i.imgur.com/1Uxvh7o.png';
	case 76:
		return 'https://i.imgur.com/aJ5Wot5.png';
	case 77:
		return 'https://i.imgur.com/5HZrSht.png';
	case 78:
		return 'https://i.imgur.com/tlACnNZ.png';
	case 79:
		return 'https://i.imgur.com/IvbAFyC.png';
	case 80:
		return 'https://i.imgur.com/o9bbZtq.png';
	case 81:
		return 'https://i.imgur.com/5jjTqtq.png';
	case 82:
		return 'https://i.imgur.com/D2w0D4C.png';
	case 83:
		return 'https://i.imgur.com/HCHzyGk.png';
	case 84:
		return 'https://i.imgur.com/xAYQ7ag.png';
	case 85:
		return 'https://i.imgur.com/sJX5o6P.png';
	case 86:
		return 'https://i.imgur.com/FTHy8hq.png';
	case 87:
		return 'https://i.imgur.com/KCUATim.png';
	case 88:
		return 'https://i.imgur.com/sl4B7ae.png';
	case 89:
		return 'https://i.imgur.com/K5t2uMG.png';
	case 90:
		return 'https://i.imgur.com/2GoaO4e.png';
	case 91:
		return 'https://i.imgur.com/LCA9V4z.png';
	case 92:
		return 'https://i.imgur.com/VN8Ko3T.png';
	case 93:
		return 'https://i.imgur.com/kYuG2uR.png';
	case 94:
		return 'https://i.imgur.com/qOBRF5d.png';
	case 95:
		return 'https://i.imgur.com/IJm1JDv.png';
	case 96:
		return 'https://i.imgur.com/AbGMpHN.png';
	case 97:
		return 'https://i.imgur.com/5FdGYPi.png';
	case 98:
		return 'https://i.imgur.com/Fnolvkh.png';
	case 99:
		return 'https://i.imgur.com/bC0uQnF.png';
	case 100:
		return 'https://i.imgur.com/vOpSwqF.png';
	case 101:
		return 'https://i.imgur.com/myJQsk2.png';
	case 102:
		return 'https://i.imgur.com/o5XSRDF.png';
	case 103:
		return 'https://i.imgur.com/Q0Ezxqa.png';
	case 104:
		return 'https://i.imgur.com/yZJHffA.png';
	case 105:
		return 'https://i.imgur.com/rJlISDK.png';
	case 106:
		return 'https://i.imgur.com/SHAaTeT.png';
	case 107:
		return 'https://i.imgur.com/7RreJNZ.png';
	case 108:
		return 'https://i.imgur.com/Rl8sAD7.png';
	case 109:
		return 'https://i.imgur.com/c1iV5pl.png';
	case 110:
		return 'https://i.imgur.com/ndLxjeH.png';
	case 111:
		return 'https://i.imgur.com/lsHhAd4.png';
	case 112:
		return 'https://i.imgur.com/mRbF6UO.png';
	case 113:
		return 'https://i.imgur.com/qHCasUZ.png';
	case 114:
		return 'https://i.imgur.com/0pCbH0t.png';
	case 115:
		return 'https://i.imgur.com/eXjjXvL.png';
	case 116:
		return 'https://i.imgur.com/tZit2rN.png';
	case 117:
		return 'https://i.imgur.com/CC9jf9C.png';
	case 118:
		return 'https://i.imgur.com/ZO4xNhc.png';
	case 119:
		return 'https://i.imgur.com/4N7XpAM.png';
	case 120:
		return 'https://i.imgur.com/OnDBZic.png';
	case 121:
		return 'https://i.imgur.com/CaKYep5.png';
	case 122:
		return 'https://i.imgur.com/n85ZARs.png';
	case 123:
		return 'https://i.imgur.com/W0tAFFk.png';
	case 124:
		return 'https://i.imgur.com/VJYIeD1.png';
	case 125:
		return 'https://i.imgur.com/7hLRVTm.png';
	case 126:
		return 'https://i.imgur.com/WHNqSEk.png';
	case 127:
		return 'https://i.imgur.com/qIibuLJ.png';
	case 128:
		return 'https://i.imgur.com/WbSj5jx.png';
	case 129:
		return 'https://i.imgur.com/g3Ivvxi.png';
	case 130:
		return 'https://i.imgur.com/qnWil3Z.png';
	case 131:
		return 'https://i.imgur.com/jrMHtru.png';
	case 132:
		return 'https://i.imgur.com/d8rV5Cu.png';
	case 133:
		return 'https://i.imgur.com/yL6KisF.png';
	case 134:
		return 'https://i.imgur.com/QPShjQM.png';
	case 135:
		return 'https://i.imgur.com/HiDcNv2.png';
	case 136:
		return 'https://i.imgur.com/V8eiLeA.png';
	case 137:
		return 'https://i.imgur.com/0SvT6IK.png';
	case 138:
		return 'https://i.imgur.com/PccjV9U.png';
	case 139:
		return 'https://i.imgur.com/K1UmZjW.png';
	case 140:
		return 'https://i.imgur.com/ZAWibC3.png';
	case 141:
		return 'https://i.imgur.com/zyfrQm7.png';
	case 142:
		return 'https://i.imgur.com/k2KlBWR.png';
	case 143:
		return 'https://i.imgur.com/BClYxdO.png';
	case 144:
		return 'https://i.imgur.com/Dber68I.png';
	case 145:
		return 'https://i.imgur.com/S6T4gON.png';
	case 146:
		return 'https://i.imgur.com/0zE2B8K.png';
	case 147:
		return 'https://i.imgur.com/wnyKVYm.png';
	case 148:
		return 'https://i.imgur.com/WnIC9xB.png';
	case 149:
		return 'https://i.imgur.com/V5GnSS3.png';
	case 150:
		return 'https://i.imgur.com/RQyXvgj.png';
	case 151:
		return 'https://i.imgur.com/0DYD4vK.png';
	case 152:
		return 'https://i.imgur.com/lYmBVPW.png';
	case 153:
		return 'https://i.imgur.com/YOMfQMr.png';
	case 154:
		return 'https://i.imgur.com/rppUvRq.png';
	case 155:
		return 'https://i.imgur.com/ipJtGrD.png';
	case 156:
		return 'https://i.imgur.com/Swwl1Be.png';
	case 157:
		return 'https://i.imgur.com/5GYzgzY.png';
	case 158:
		return 'https://i.imgur.com/vW7TxgP.png';
	case 159:
		return 'https://i.imgur.com/aRiaVVs.png';
	case 160:
		return 'https://i.imgur.com/LCuPQ5b.png';
	case 161:
		return 'https://i.imgur.com/lkEDBiB.png';
	case 162:
		return 'https://i.imgur.com/R5f7eI6.png';
	case 163:
		return 'https://i.imgur.com/azgJ1I5.png';
	case 164:
		return 'https://i.imgur.com/ort4ulb.png';
	case 165:
		return 'https://i.imgur.com/FfNAsA6.png';
	case 166:
		return 'https://i.imgur.com/3RySEZo.png';
	case 167:
		return 'https://i.imgur.com/VwdI5Aj.png';
	case 168:
		return 'https://i.imgur.com/calvPZA.png';
	case 169:
		return 'https://i.imgur.com/iW1ife8.png';
	case 170:
		return 'https://i.imgur.com/3fvsmQo.png';
	case 171:
		return 'https://i.imgur.com/ZZSTUj2.png';
	case 172:
		return 'https://i.imgur.com/uNvKXZn.png';
	case 173:
		return 'https://i.imgur.com/7Lw7lmV.png';
	case 174:
		return 'https://i.imgur.com/fGqkQKm.png';
	case 175:
		return 'https://i.imgur.com/Sv4bcpo.png';
	case 176:
		return 'https://i.imgur.com/LO8DwDu.png';
	case 177:
		return 'https://i.imgur.com/upmetoT.png';
	case 178:
		return 'https://i.imgur.com/h54XXr1.png';
	case 179:
		return 'https://i.imgur.com/Ao4pqdy.png';
	case 180:
		return 'https://i.imgur.com/0MvhT8r.png';
	case 181:
		return 'https://i.imgur.com/vQ7a1ar.png';
	case 182:
		return 'https://i.imgur.com/yLWhos0.png';
	case 183:
		return 'https://i.imgur.com/LiuXqZ9.png';
	case 184:
		return 'https://i.imgur.com/05ufIFP.png';
	case 185:
		return 'https://i.imgur.com/VkFj5oJ.png';
	case 186:
		return 'https://i.imgur.com/eKWZEAM.png';
	case 187:
		return 'https://i.imgur.com/fK2HSi0.png';
	case 188:
		return 'https://i.imgur.com/gkrfDOe.png';
	case 189:
		return 'https://i.imgur.com/RkfD2la.png';
	case 190:
		return 'https://i.imgur.com/tDMBArK.png';
	case 191:
		return 'https://i.imgur.com/UwA3ss8.png';
	case 192:
		return 'https://i.imgur.com/RNxDcaR.png';
	case 193:
		return 'https://i.imgur.com/CfbQ8rk.png';
	case 194:
		return 'https://i.imgur.com/tzOCifq.png';
	case 195:
		return 'https://i.imgur.com/pF2qPhe.png';
	case 196:
		return 'https://i.imgur.com/Jvsl1QN.png';
	case 197:
		return 'https://i.imgur.com/Q5JC887.png';
	case 198:
		return 'https://i.imgur.com/zKxb5CD.png';
	case 199:
		return 'https://i.imgur.com/57rldE7.png';
	case 200:
		return 'https://i.imgur.com/p9uxItX.png';
	case 201:
		return 'https://i.imgur.com/GOSKeMY.png';
	case 202:
		return 'https://i.imgur.com/wyuJK4z.png';
	case 203:
		return 'https://i.imgur.com/E2fCVYA.png';
	case 204:
		return 'https://i.imgur.com/iXSn3iV.png';
	case 205:
		return 'https://i.imgur.com/0sPFxER.png';
	case 206:
		return 'https://i.imgur.com/4VrcSg4.png';
	case 207:
		return 'https://i.imgur.com/XyraRwb.png';
	case 208:
		return 'https://i.imgur.com/ETN0i62.png';
	case 209:
		return 'https://i.imgur.com/Q077R8j.png';
	case 210:
		return 'https://i.imgur.com/bFkxn3W.png';
	case 211:
		return 'https://i.imgur.com/qag62mn.png';
	case 212:
		return 'https://i.imgur.com/CiFlsLg.png';
	case 213:
		return 'https://i.imgur.com/k0FGZrV.png';
	case 214:
		return 'https://i.imgur.com/LbNMpKd.png';
	case 215:
		return 'https://i.imgur.com/dEckRQB.png';
	case 216:
		return 'https://i.imgur.com/UT2Cg4y.png';
	case 217:
		return 'https://i.imgur.com/6IM7SBt.png';
	case 218:
		return 'https://i.imgur.com/rLhLgUG.png';
	case 219:
		return 'https://i.imgur.com/x2Olf0V.png';
	case 220:
		return 'https://i.imgur.com/wLH94tv.png';
	case 221:
		return 'https://i.imgur.com/OoLuHYQ.png';
	case 222:
		return 'https://i.imgur.com/56WJTUP.png';
	case 223:
		return 'https://i.imgur.com/Isol4m8.png';
	case 224:
		return 'https://i.imgur.com/1HvsAVH.png';
	case 225:
		return 'https://i.imgur.com/UbaKPWI.png';
	case 226:
		return 'https://i.imgur.com/SqoTOrK.png';
	case 227:
		return 'https://i.imgur.com/hihVgLF.png';
	case 228:
		return 'https://i.imgur.com/ehyHT8W.png';
	case 229:
		return 'https://i.imgur.com/DEC1YZ5.png';
	case 230:
		return 'https://i.imgur.com/kHYkUbT.png';
	case 231:
		return 'https://i.imgur.com/TuJMX4l.png';
	case 232:
		return 'https://i.imgur.com/oEpJA7O.png';
	case 233:
		return 'https://i.imgur.com/SSHIs1D.png';
	case 234:
		return 'https://i.imgur.com/7n2lS6Q.png';
	case 235:
		return 'https://i.imgur.com/YgyqEvf.png';
	case 236:
		return 'https://i.imgur.com/EoeMOcu.png';
	case 237:
		return 'https://i.imgur.com/FJTWkL8.png';
	case 238:
		return 'https://i.imgur.com/FGGvDUW.png';
	case 239:
		return 'https://i.imgur.com/1uIqWwa.png';
	case 240:
		return 'https://i.imgur.com/gYGuLoy.png';
	case 241:
		return 'https://i.imgur.com/9w8amaS.png';
	case 242:
		return 'https://i.imgur.com/PdPxbKy.png';
	case 243:
		return 'https://i.imgur.com/9RrcQmQ.png';
	case 244:
		return 'https://i.imgur.com/YlaR3JR.png';
	case 245:
		return 'https://i.imgur.com/kuQdldC.png';
	case 246:
		return 'https://i.imgur.com/Lza5QbT.png';
	case 247:
		return 'https://i.imgur.com/51ZTpDy.png';
	case 248:
		return 'https://i.imgur.com/Vdw2q9A.png';
	case 249:
		return 'https://i.imgur.com/K1mENIl.png';
	case 250:
		return 'https://i.imgur.com/KOr2hd5.png';
	case 251:
		return 'https://i.imgur.com/yY60Asz.png';
	case 252:
		return 'https://i.imgur.com/4InvSMj.png';
	case 253:
		return 'https://i.imgur.com/4rMjUer.png';
	case 254:
		return 'https://i.imgur.com/6Vt30Ap.png';
	case 255:
		return 'https://i.imgur.com/QPPo70a.png';
	case 256:
		return 'https://i.imgur.com/3G12aPY.png';
	case 257:
		return 'https://i.imgur.com/WqDuoAJ.png';
	case 258:
		return 'https://i.imgur.com/z5T7R3x.png';
	case 259:
		return 'https://i.imgur.com/m5DI2P3.png';
	case 260:
		return 'https://i.imgur.com/QaRg1mO.png';
	case 261:
		return 'https://i.imgur.com/4O17bqk.png';
	case 262:
		return 'https://i.imgur.com/gLGUPSY.png';
	case 263:
		return 'https://i.imgur.com/L0Rk0sW.png';
	case 264:
		return 'https://i.imgur.com/QMBsL7E.png';
	case 265:
		return 'https://i.imgur.com/l81q7zo.png';
	case 266:
		return 'https://i.imgur.com/l2BUkF9.png';
	case 267:
		return 'https://i.imgur.com/JRjfxFm.png';
	case 268:
		return 'https://i.imgur.com/8XQWs4n.png';
	case 269:
		return 'https://i.imgur.com/ddiqlGQ.png';
	case 270:
		return 'https://i.imgur.com/uVkJxcq.png';
	case 271:
		return 'https://i.imgur.com/uOABhNG.png';
	case 272:
		return 'https://i.imgur.com/1lDcnx3.png';
	case 273:
		return 'https://i.imgur.com/mERdHf2.png';
	case 274:
		return 'https://i.imgur.com/SwhuXKa.png';
	case 275:
		return 'https://i.imgur.com/NMoXANX.png';
	case 276:
		return 'https://i.imgur.com/ctFQgTa.png';
	case 277:
		return 'https://i.imgur.com/9E9BJNl.png';
	case 278:
		return 'https://i.imgur.com/tHaY3qD.png';
	case 279:
		return 'https://i.imgur.com/8szfEKT.png';
	case 280:
		return 'https://i.imgur.com/JSm4DDW.png';
	case 281:
		return 'https://i.imgur.com/MbrK4Ux.png';
	case 282:
		return 'https://i.imgur.com/mFixa9F.png';
	case 283:
		return 'https://i.imgur.com/5ylS7hB.png';
	case 284:
		return 'https://i.imgur.com/DQ2mW59.png';
	case 285:
		return 'https://i.imgur.com/QNglaRp.png';
	case 286:
		return 'https://i.imgur.com/oJ84MsW.png';
	case 287:
		return 'https://i.imgur.com/XeRC8jv.png';
	case 288:
		return 'https://i.imgur.com/WT9ZHNT.png';
	case 289:
		return 'https://i.imgur.com/Gt3rezD.png';
	case 290:
		return 'https://i.imgur.com/62fjSWP.png';
	case 291:
		return 'https://i.imgur.com/jgKP2l5.png';
	case 292:
		return 'https://i.imgur.com/hfYq6oH.png';
	case 293:
		return 'https://i.imgur.com/uODrRQg.png';
	case 294:
		return 'https://i.imgur.com/nW3vnYj.png';
	case 295:
		return 'https://i.imgur.com/uCLFc6i.png';
	case 296:
		return 'https://i.imgur.com/5V4M2bN.png';
	case 297:
		return 'https://i.imgur.com/BiULIWe.png';
	case 298:
		return 'https://i.imgur.com/JRwvOAD.png';
	case 299:
		return 'https://i.imgur.com/TwnvNAh.png';
	case 300:
		return 'https://i.imgur.com/cwslOYP.png';
	case 301:
		return 'https://i.imgur.com/wTK4vBq.png';
	case 302:
		return 'https://i.imgur.com/8nuvzzy.png';
	case 303:
		return 'https://i.imgur.com/XCp8p0r.png';
	case 304:
		return 'https://i.imgur.com/i0gJ0PN.png';
	case 305:
		return 'https://i.imgur.com/cshs8iE.png';
	case 306:
		return 'https://i.imgur.com/OBKnZtL.png';
	case 307:
		return 'https://i.imgur.com/YGnYm4Y.png';
	case 308:
		return 'https://i.imgur.com/4n9ISZ7.png';
	case 309:
		return 'https://i.imgur.com/B5oLkkb.png';
	case 310:
		return 'https://i.imgur.com/fIdeUw7.png';
	case 311:
		return 'https://i.imgur.com/AnKZ501.png';
	case 312:
		return 'https://i.imgur.com/Mxtxrz0.png';
	case 313:
		return 'https://i.imgur.com/4fkAXHo.png';
	case 314:
		return 'https://i.imgur.com/fkuqfsj.png';
	case 315:
		return 'https://i.imgur.com/WMlbAY8.png';
	case 316:
		return 'https://i.imgur.com/IS4d8w1.png';
	case 317:
		return 'https://i.imgur.com/hehKrOR.png';
	case 318:
		return 'https://i.imgur.com/Un0thMc.png';
	case 319:
		return 'https://i.imgur.com/h6ddYtJ.png';
	case 320:
		return 'https://i.imgur.com/cw6hlDS.png';
	case 321:
		return 'https://i.imgur.com/2gGNayR.png';
	case 322:
		return 'https://i.imgur.com/RdPnNGT.png';
	case 323:
		return 'https://i.imgur.com/94dLNGG.png';
	case 324:
		return 'https://i.imgur.com/zm8D9tP.png';
	case 325:
		return 'https://i.imgur.com/h8zNnmo.png';
	case 326:
		return 'https://i.imgur.com/fu5sf1X.png';
	case 327:
		return 'https://i.imgur.com/BXMpaEc.png';
	case 328:
		return 'https://i.imgur.com/jXZ8BkI.png';
	case 329:
		return 'https://i.imgur.com/Oz0y3mO.png';
	case 330:
		return 'https://i.imgur.com/RMbKYhH.png';
	case 331:
		return 'https://i.imgur.com/s6nKnp5.png';
	case 332:
		return 'https://i.imgur.com/Sd6uiBG.png';
	case 333:
		return 'https://i.imgur.com/D162WYP.png';
	case 334:
		return 'https://i.imgur.com/wytXus4.png';
	case 335:
		return 'https://i.imgur.com/aCrdfPr.png';
	case 336:
		return 'https://i.imgur.com/6p6GX63.png';
	case 337:
		return 'https://i.imgur.com/OVMkFrM.png';
	case 338:
		return 'https://i.imgur.com/RSfDitn.png';
	case 339:
		return 'https://i.imgur.com/s05Xe7G.png';
	case 340:
		return 'https://i.imgur.com/QkjoFHi.png';
	case 341:
		return 'https://i.imgur.com/ARjcbRn.png';
	case 342:
		return 'https://i.imgur.com/6C4cEN0.png';
	case 343:
		return 'https://i.imgur.com/UP746S5.png';
	case 344:
		return 'https://i.imgur.com/Hxw5cFZ.png';
	case 345:
		return 'https://i.imgur.com/qmL1Zp5.png';
	case 346:
		return 'https://i.imgur.com/1HBeW4M.png';
	case 347:
		return 'https://i.imgur.com/4G02CCF.png';
	case 348:
		return 'https://i.imgur.com/QspwMHJ.png';
	case 349:
		return 'https://i.imgur.com/mS36sqi.png';
	case 350:
		return 'https://i.imgur.com/b5YMULg.png';
	case 351:
		return 'https://i.imgur.com/yDlHzag.png';
	case 352:
		return 'https://i.imgur.com/usF0uju.png';
	case 353:
		return 'https://i.imgur.com/7xoQfBe.png';
	}
}

function findCheese(ran) {
	switch(ran) {
	case 1:
		return 'https://i.imgur.com/oUVUqJu.jpg';
	case 2:
		return 'https://i.imgur.com/qJuyMDV.jpg';
	case 3:
		return 'https://i.imgur.com/fUUGKdf.jpg';
	case 4:
		return 'https://i.imgur.com/GXA3wxA.jpg';
	case 5:
		return 'https://i.imgur.com/MM0PEV2.jpg';
	case 6:
		return 'https://i.imgur.com/RJ5LM9d.jpg';
	case 7:
		return 'https://i.imgur.com/G6YbdNd.jpg';
	case 8:
		return 'https://i.imgur.com/JphX4mQ.jpg';
	case 9:
		return 'https://i.imgur.com/K7thU6P.jpg';
	case 10:
		return 'https://i.imgur.com/SIWUBUX.jpg';
	case 11:
		return 'https://i.imgur.com/YJry2yd.jpg';
	case 12:
		return 'https://i.imgur.com/RqzNMgK.jpg';
	case 13:
		return 'https://i.imgur.com/p39PAyO.jpg';
	case 14:
		return 'https://i.imgur.com/UjqICqh.jpg';
	case 15:
		return 'https://i.imgur.com/ZAJLmUv.jpg';
	}
}

function findBocchi(ran) {
	switch(ran) {
	case 1:
		return 'https://i.imgur.com/wjVM31a.png';
	case 2:
		return 'https://i.imgur.com/kQFrZQ0.png';
	case 3:
		return 'https://i.imgur.com/tqMt5a8.png';
	case 4:
		return 'https://i.imgur.com/CD0VAks.png';
	case 5:
		return 'https://i.imgur.com/IaHenWt.png';
	case 6:
		return 'https://i.imgur.com/ALYHOG4.png';
	case 7:
		return 'https://i.imgur.com/5raB5DM.png';
	case 8:
		return 'https://i.imgur.com/Xk51MqZ.png';
	case 9:
		return 'https://i.imgur.com/c6kSMTU.png';
	case 10:
		return 'https://i.imgur.com/net548m.png';
	case 11:
		return 'https://i.imgur.com/I8QNd2k.png';
	case 12:
		return 'https://i.imgur.com/8Q6kZtt.png';
	case 13:
		return 'https://i.imgur.com/7v3FEF6.png';
	case 14:
		return 'https://i.imgur.com/ACsuL7Z.png';
	case 15:
		return 'https://i.imgur.com/LaWkg0G.png';
	case 16:
		return 'https://i.imgur.com/hDSj2Wm.png';
	case 17:
		return 'https://i.imgur.com/lImdBn0.png';
	case 18:
		return 'https://i.imgur.com/cX7yXoe.png';
	case 19:
		return 'https://i.imgur.com/zYPORni.png';
	case 20:
		return 'https://i.imgur.com/syxFKBx.png';
	case 21:
		return 'https://i.imgur.com/ArfiZYE.png';
	case 22:
		return 'https://i.imgur.com/9RD8dd6.png';
	case 23:
		return 'https://i.imgur.com/2bvBnEa.png';
	case 24:
		return 'https://i.imgur.com/T7EUmdl.png';
	case 25:
		return 'https://i.imgur.com/YoWRxiu.png';
	case 26:
		return 'https://i.imgur.com/xEeQy6U.png';
	case 27:
		return 'https://i.imgur.com/IYHmrwm.png';
	case 28:
		return 'https://i.imgur.com/W0d6QfE.png';
	case 29:
		return 'https://i.imgur.com/NoqHlcG.png';
	case 30:
		return 'https://i.imgur.com/gwkFNsr.png';
	case 31:
		return 'https://i.imgur.com/GyY1JdR.png';
	case 32:
		return 'https://i.imgur.com/yBWaCY1.png';
	case 33:
		return 'https://i.imgur.com/b3Ge2uR.png';
	case 34:
		return 'https://i.imgur.com/ni0sQ9V.png';
	case 35:
		return 'https://i.imgur.com/cmasjAd.png';
	case 36:
		return 'https://i.imgur.com/t1SYgl0.png';
	case 37:
		return 'https://i.imgur.com/5iANaXk.png';
	case 38:
		return 'https://i.imgur.com/gwJ2E0z.png';
	case 39:
		return 'https://i.imgur.com/4eXfMRi.png';
	case 40:
		return 'https://i.imgur.com/ZrhBArG.png';
	case 41:
		return 'https://i.imgur.com/YWtDx6U.png';
	case 42:
		return 'https://i.imgur.com/8SkxT0E.png';
	case 43:
		return 'https://i.imgur.com/36W7Nda.png';
	case 44:
		return 'https://i.imgur.com/7gudfQB.png';
	case 45:
		return 'https://i.imgur.com/4X1PkfW.png';
	case 46:
		return 'https://i.imgur.com/SAb3B6m.png';
	case 47:
		return 'https://i.imgur.com/RvZYXBc.png';
	case 48:
		return 'https://i.imgur.com/jTSqEhk.png';
	case 49:
		return 'https://i.imgur.com/b4RUZfF.png';
	case 50:
		return 'https://i.imgur.com/WCTibMH.png';
	case 51:
		return 'https://i.imgur.com/AFoUDV7.png';
	case 52:
		return 'https://i.imgur.com/QTHkCda.png';
	case 53:
		return 'https://i.imgur.com/H3CP0KZ.png';
	case 54:
		return 'https://i.imgur.com/GUigsnS.png';
	case 55:
		return 'https://i.imgur.com/20BK5ui.png';
	case 56:
		return 'https://i.imgur.com/AtxZpsi.png';
	case 57:
		return 'https://i.imgur.com/LnXHJi4.png';
	case 58:
		return 'https://i.imgur.com/x2m7OBX.png';
	case 59:
		return 'https://i.imgur.com/yaH8QQL.png';
	case 60:
		return 'https://i.imgur.com/jab2xES.png';
	}
}

function findCry(ran) {
	switch(ran) {
	case 1:
		return 'https://media1.tenor.com/images/ce52606293142a2bd11cda1d3f0dc12c/tenor.gif?itemid=5184314';
	case 2:
		return 'https://media1.tenor.com/images/e69ebde3631408c200777ebe10f84367/tenor.gif?itemid=5081296';
	case 3:
		return 'https://media1.tenor.com/images/b88fa314f0f172832a5f41fce111f359/tenor.gif?itemid=13356071';
	case 4:
		return 'https://media1.tenor.com/images/75edc9882e5175f86c2af777ffbb14a6/tenor.gif?itemid=5755232';
	case 5:
		return 'https://media1.tenor.com/images/04b0feb0e2e6861d5e57c1cb2cdb4dd9/tenor.gif?itemid=10810456';
	case 6:
		return 'https://media1.tenor.com/images/9ac0a766ee58c2ac7d24f3da8ebb970d/tenor.gif?itemid=16521935';
	case 7:
		return 'https://media1.tenor.com/images/8d4dd59c053f9a8af24795ffb9507120/tenor.gif?itemid=13988059';
	case 8:
		return 'https://media1.tenor.com/images/83b732c53bfdd1409aec0553f9bfacfd/tenor.gif?itemid=15974226';
	}
}

function findKiss(ran) {
	switch(ran) {
	case 1:
		return 'https://media1.tenor.com/images/68d07bdc2be6477c71f592f4325f52e4/tenor.gif?itemid=12434266';
	case 2:
		return 'https://media1.tenor.com/images/7de89bb0f49de7bb987f0c3908998cd6/tenor.gif?itemid=19827352';
	case 3:
		return 'https://media1.tenor.com/images/503bb007a3c84b569153dcfaaf9df46a/tenor.gif?itemid=17382412';
	case 4:
		return 'https://media1.tenor.com/images/3d56f6ef81e5c01241ff17c364b72529/tenor.gif?itemid=13843260';
	case 5:
		return 'https://media1.tenor.com/images/9fac3eab2f619789b88fdf9aa5ca7b8f/tenor.gif?itemid=12925177';
	case 6:
		return 'https://media1.tenor.com/images/558f63303a303abfdddaa71dc7b3d6ae/tenor.gif?itemid=12879850';
	case 7:
		return 'https://media1.tenor.com/images/8f123ea8701cba00d56b4069dbb3c7cc/tenor.gif?itemid=15988106';
	}
}

function findPunch(ran) {
	switch(ran) {
	case 1:
		return 'https://media1.tenor.com/images/e7ec62e9618d3b7f4bf1c14247dad437/tenor.gif?itemid=21062825';
	case 2:
		return 'https://media1.tenor.com/images/31686440e805309d34e94219e4bedac1/tenor.gif?itemid=4790446';
	case 3:
		return 'https://media1.tenor.com/images/2487a7679b3d7d23cadcd51381635467/tenor.gif?itemid=11451829';
	case 4:
		return 'https://media1.tenor.com/images/b746bc37f2e29185523b1b7a0df45fdd/tenor.gif?itemid=19285337';
	case 5:
		return 'https://media1.tenor.com/images/55507aea306782b916659085fc062909/tenor.gif?itemid=8932977';
	case 6:
		return 'https://media1.tenor.com/images/19ecddffb14e87a4b6277a9fdb18b8e0/tenor.gif?itemid=15018384';
	case 7:
		return 'https://media1.tenor.com/images/855c900190fb6abfabaed7da4da6f73c/tenor.gif?itemid=16962926';
	case 8:
		return 'https://media1.tenor.com/images/0e5afd72b5c5c9b3ba61df8c39c3e590/tenor.gif?itemid=19594599';
	}
}

module.exports = { findHug, title, color, payout, gambleRoll, gambleValue, findGif, findImage, randomSwitchHub, findImas, findCheese, findBocchi, findCry, findKiss, findPunch };